/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StepAction } from './StepAction';
import {
    StepActionFromJSON,
    StepActionFromJSONTyped,
    StepActionToJSON,
    StepActionToJSONTyped,
} from './StepAction';

/**
 * 
 * @export
 * @interface AcceptCredentialAction
 */
export interface AcceptCredentialAction extends StepAction {
    /**
     * Credential definition ID
     * @type {string}
     * @memberof AcceptCredentialAction
     */
    credentialDefinitionId: string;
    /**
     * Connection ID
     * @type {string}
     * @memberof AcceptCredentialAction
     */
    connectionId?: string;
}

/**
 * Check if a given object implements the AcceptCredentialAction interface.
 */
export function instanceOfAcceptCredentialAction(value: object): value is AcceptCredentialAction {
    if (!('credentialDefinitionId' in value) || value['credentialDefinitionId'] === undefined) return false;
    return true;
}

export function AcceptCredentialActionFromJSON(json: any): AcceptCredentialAction {
    return AcceptCredentialActionFromJSONTyped(json, false);
}

export function AcceptCredentialActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptCredentialAction {
    if (json == null) {
        return json;
    }
    return {
        ...StepActionFromJSONTyped(json, true),
        'credentialDefinitionId': json['credentialDefinitionId'],
        'connectionId': json['connectionId'] == null ? undefined : json['connectionId'],
    };
}

export function AcceptCredentialActionToJSON(json: any): AcceptCredentialAction {
    return AcceptCredentialActionToJSONTyped(json, false);
}

export function AcceptCredentialActionToJSONTyped(value?: AcceptCredentialAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...StepActionToJSONTyped(value, true),
        'credentialDefinitionId': value['credentialDefinitionId'],
        'connectionId': value['connectionId'],
    };
}

