/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Anonymous Credentials specific revocation information
 * @export
 * @interface AnonCredRevocation
 */
export interface AnonCredRevocation {
    /**
     * Id of the revocation information
     * @type {string}
     * @memberof AnonCredRevocation
     */
    id: string;
    /**
     * Title of the revocation information
     * @type {string}
     * @memberof AnonCredRevocation
     */
    title: string;
    /**
     * Detailed description of the revocation process or requirements
     * @type {string}
     * @memberof AnonCredRevocation
     */
    description: string;
    /**
     * Date and time the Revocation info was created
     * @type {Date}
     * @memberof AnonCredRevocation
     */
    createdAt: Date;
    /**
     * Date and time the Revocation info was last updated
     * @type {Date}
     * @memberof AnonCredRevocation
     */
    updatedAt: Date;
    /**
     * Identifier of the revocation registry for AnonCreds
     * @type {string}
     * @memberof AnonCredRevocation
     */
    registryId: string;
}

/**
 * Check if a given object implements the AnonCredRevocation interface.
 */
export function instanceOfAnonCredRevocation(value: object): value is AnonCredRevocation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('registryId' in value) || value['registryId'] === undefined) return false;
    return true;
}

export function AnonCredRevocationFromJSON(json: any): AnonCredRevocation {
    return AnonCredRevocationFromJSONTyped(json, false);
}

export function AnonCredRevocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnonCredRevocation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'registryId': json['registryId'],
    };
}

export function AnonCredRevocationToJSON(json: any): AnonCredRevocation {
    return AnonCredRevocationToJSONTyped(json, false);
}

export function AnonCredRevocationToJSONTyped(value?: AnonCredRevocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'registryId': value['registryId'],
    };
}

