/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AriesRequestCredentialPredicates
 */
export interface AriesRequestCredentialPredicates {
    /**
     * Name of the attribute for predicate
     * @type {string}
     * @memberof AriesRequestCredentialPredicates
     */
    name: string;
    /**
     * Type of predicate (e.g., >=, <=, etc.)
     * @type {string}
     * @memberof AriesRequestCredentialPredicates
     */
    type: string;
    /**
     * Value to compare against
     * @type {string}
     * @memberof AriesRequestCredentialPredicates
     */
    value: string;
    /**
     * List of restrictions on the predicate
     * @type {Array<string>}
     * @memberof AriesRequestCredentialPredicates
     */
    restrictions: Array<string>;
}

/**
 * Check if a given object implements the AriesRequestCredentialPredicates interface.
 */
export function instanceOfAriesRequestCredentialPredicates(value: object): value is AriesRequestCredentialPredicates {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('restrictions' in value) || value['restrictions'] === undefined) return false;
    return true;
}

export function AriesRequestCredentialPredicatesFromJSON(json: any): AriesRequestCredentialPredicates {
    return AriesRequestCredentialPredicatesFromJSONTyped(json, false);
}

export function AriesRequestCredentialPredicatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AriesRequestCredentialPredicates {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'value': json['value'],
        'restrictions': json['restrictions'],
    };
}

export function AriesRequestCredentialPredicatesToJSON(json: any): AriesRequestCredentialPredicates {
    return AriesRequestCredentialPredicatesToJSONTyped(json, false);
}

export function AriesRequestCredentialPredicatesToJSONTyped(value?: AriesRequestCredentialPredicates | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'value': value['value'],
        'restrictions': value['restrictions'],
    };
}

