/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AriesProofRequest } from './AriesProofRequest';
import {
    AriesProofRequestFromJSON,
    AriesProofRequestFromJSONTyped,
    AriesProofRequestToJSON,
    AriesProofRequestToJSONTyped,
} from './AriesProofRequest';
import type { StepAction } from './StepAction';
import {
    StepActionFromJSON,
    StepActionFromJSONTyped,
    StepActionToJSON,
    StepActionToJSONTyped,
} from './StepAction';

/**
 * 
 * @export
 * @interface AriesOOBAction
 */
export interface AriesOOBAction extends StepAction {
    /**
     * 
     * @type {AriesProofRequest}
     * @memberof AriesOOBAction
     */
    proofRequest: AriesProofRequest;
}

/**
 * Check if a given object implements the AriesOOBAction interface.
 */
export function instanceOfAriesOOBAction(value: object): value is AriesOOBAction {
    if (!('proofRequest' in value) || value['proofRequest'] === undefined) return false;
    return true;
}

export function AriesOOBActionFromJSON(json: any): AriesOOBAction {
    return AriesOOBActionFromJSONTyped(json, false);
}

export function AriesOOBActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AriesOOBAction {
    if (json == null) {
        return json;
    }
    return {
        ...StepActionFromJSONTyped(json, true),
        'proofRequest': AriesProofRequestFromJSON(json['proofRequest']),
    };
}

export function AriesOOBActionToJSON(json: any): AriesOOBAction {
    return AriesOOBActionToJSONTyped(json, false);
}

export function AriesOOBActionToJSONTyped(value?: AriesOOBAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...StepActionToJSONTyped(value, true),
        'proofRequest': AriesProofRequestToJSON(value['proofRequest']),
    };
}

