/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AriesRequestCredentialAttributes } from './AriesRequestCredentialAttributes';
import {
    AriesRequestCredentialAttributesFromJSON,
    AriesRequestCredentialAttributesFromJSONTyped,
    AriesRequestCredentialAttributesToJSON,
    AriesRequestCredentialAttributesToJSONTyped,
} from './AriesRequestCredentialAttributes';
import type { AriesRequestCredentialPredicates } from './AriesRequestCredentialPredicates';
import {
    AriesRequestCredentialPredicatesFromJSON,
    AriesRequestCredentialPredicatesFromJSONTyped,
    AriesRequestCredentialPredicatesToJSON,
    AriesRequestCredentialPredicatesToJSONTyped,
} from './AriesRequestCredentialPredicates';

/**
 * 
 * @export
 * @interface AriesProofRequestRequest
 */
export interface AriesProofRequestRequest {
    /**
     * Map of attribute groups requested in the proof
     * @type {{ [key: string]: AriesRequestCredentialAttributes; }}
     * @memberof AriesProofRequestRequest
     */
    attributes: { [key: string]: AriesRequestCredentialAttributes; };
    /**
     * Map of predicate groups requested in the proof
     * @type {{ [key: string]: AriesRequestCredentialPredicates; }}
     * @memberof AriesProofRequestRequest
     */
    predicates: { [key: string]: AriesRequestCredentialPredicates; };
}

/**
 * Check if a given object implements the AriesProofRequestRequest interface.
 */
export function instanceOfAriesProofRequestRequest(value: object): value is AriesProofRequestRequest {
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    if (!('predicates' in value) || value['predicates'] === undefined) return false;
    return true;
}

export function AriesProofRequestRequestFromJSON(json: any): AriesProofRequestRequest {
    return AriesProofRequestRequestFromJSONTyped(json, false);
}

export function AriesProofRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AriesProofRequestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'attributes': (mapValues(json['attributes'], AriesRequestCredentialAttributesFromJSON)),
        'predicates': (mapValues(json['predicates'], AriesRequestCredentialPredicatesFromJSON)),
    };
}

export function AriesProofRequestRequestToJSON(json: any): AriesProofRequestRequest {
    return AriesProofRequestRequestToJSONTyped(json, false);
}

export function AriesProofRequestRequestToJSONTyped(value?: AriesProofRequestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributes': (mapValues(value['attributes'], AriesRequestCredentialAttributesToJSON)),
        'predicates': (mapValues(value['predicates'], AriesRequestCredentialPredicatesToJSON)),
    };
}

