/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AriesProofRequestRequest } from './AriesProofRequestRequest';
import {
    AriesProofRequestRequestFromJSON,
    AriesProofRequestRequestFromJSONTyped,
    AriesProofRequestRequestToJSON,
    AriesProofRequestRequestToJSONTyped,
} from './AriesProofRequestRequest';
import type { StepActionRequest } from './StepActionRequest';
import {
    StepActionRequestFromJSON,
    StepActionRequestFromJSONTyped,
    StepActionRequestToJSON,
    StepActionRequestToJSONTyped,
} from './StepActionRequest';

/**
 * 
 * @export
 * @interface AriesOOBActionRequest
 */
export interface AriesOOBActionRequest extends StepActionRequest {
    /**
     * 
     * @type {AriesProofRequestRequest}
     * @memberof AriesOOBActionRequest
     */
    proofRequest: AriesProofRequestRequest;
}

/**
 * Check if a given object implements the AriesOOBActionRequest interface.
 */
export function instanceOfAriesOOBActionRequest(value: object): value is AriesOOBActionRequest {
    if (!('proofRequest' in value) || value['proofRequest'] === undefined) return false;
    return true;
}

export function AriesOOBActionRequestFromJSON(json: any): AriesOOBActionRequest {
    return AriesOOBActionRequestFromJSONTyped(json, false);
}

export function AriesOOBActionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AriesOOBActionRequest {
    if (json == null) {
        return json;
    }
    return {
        ...StepActionRequestFromJSONTyped(json, true),
        'proofRequest': AriesProofRequestRequestFromJSON(json['proofRequest']),
    };
}

export function AriesOOBActionRequestToJSON(json: any): AriesOOBActionRequest {
    return AriesOOBActionRequestToJSONTyped(json, false);
}

export function AriesOOBActionRequestToJSONTyped(value?: AriesOOBActionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...StepActionRequestToJSONTyped(value, true),
        'proofRequest': AriesProofRequestRequestToJSON(value['proofRequest']),
    };
}

