/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AriesRequestCredentialAttributes } from './AriesRequestCredentialAttributes';
import {
    AriesRequestCredentialAttributesFromJSON,
    AriesRequestCredentialAttributesFromJSONTyped,
    AriesRequestCredentialAttributesToJSON,
    AriesRequestCredentialAttributesToJSONTyped,
} from './AriesRequestCredentialAttributes';
import type { AriesRequestCredentialPredicates } from './AriesRequestCredentialPredicates';
import {
    AriesRequestCredentialPredicatesFromJSON,
    AriesRequestCredentialPredicatesFromJSONTyped,
    AriesRequestCredentialPredicatesToJSON,
    AriesRequestCredentialPredicatesToJSONTyped,
} from './AriesRequestCredentialPredicates';

/**
 * 
 * @export
 * @interface AriesProofRequest
 */
export interface AriesProofRequest {
    /**
     * Map of attribute groups requested in the proof
     * @type {{ [key: string]: AriesRequestCredentialAttributes; }}
     * @memberof AriesProofRequest
     */
    attributes: { [key: string]: AriesRequestCredentialAttributes; };
    /**
     * Map of predicate groups requested in the proof
     * @type {{ [key: string]: AriesRequestCredentialPredicates; }}
     * @memberof AriesProofRequest
     */
    predicates: { [key: string]: AriesRequestCredentialPredicates; };
    /**
     * Date and time the Aries proof request was created
     * @type {Date}
     * @memberof AriesProofRequest
     */
    createdAt?: Date;
    /**
     * Date and time the Aries proof request was last updated
     * @type {Date}
     * @memberof AriesProofRequest
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the AriesProofRequest interface.
 */
export function instanceOfAriesProofRequest(value: object): value is AriesProofRequest {
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    if (!('predicates' in value) || value['predicates'] === undefined) return false;
    return true;
}

export function AriesProofRequestFromJSON(json: any): AriesProofRequest {
    return AriesProofRequestFromJSONTyped(json, false);
}

export function AriesProofRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AriesProofRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'attributes': (mapValues(json['attributes'], AriesRequestCredentialAttributesFromJSON)),
        'predicates': (mapValues(json['predicates'], AriesRequestCredentialPredicatesFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function AriesProofRequestToJSON(json: any): AriesProofRequest {
    return AriesProofRequestToJSONTyped(json, false);
}

export function AriesProofRequestToJSONTyped(value?: AriesProofRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributes': (mapValues(value['attributes'], AriesRequestCredentialAttributesToJSON)),
        'predicates': (mapValues(value['predicates'], AriesRequestCredentialPredicatesToJSON)),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

