/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StepAction } from './StepAction';
import {
    StepActionFromJSON,
    StepActionFromJSONTyped,
    StepActionToJSON,
    StepActionToJSONTyped,
} from './StepAction';

/**
 * 
 * @export
 * @interface ButtonAction
 */
export interface ButtonAction extends StepAction {
    /**
     * Step ID
     * @type {string}
     * @memberof ButtonAction
     */
    goToStep?: string;
}

/**
 * Check if a given object implements the ButtonAction interface.
 */
export function instanceOfButtonAction(value: object): value is ButtonAction {
    return true;
}

export function ButtonActionFromJSON(json: any): ButtonAction {
    return ButtonActionFromJSONTyped(json, false);
}

export function ButtonActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ButtonAction {
    if (json == null) {
        return json;
    }
    return {
        ...StepActionFromJSONTyped(json, true),
        'goToStep': json['goToStep'] == null ? undefined : json['goToStep'],
    };
}

export function ButtonActionToJSON(json: any): ButtonAction {
    return ButtonActionToJSONTyped(json, false);
}

export function ButtonActionToJSONTyped(value?: ButtonAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...StepActionToJSONTyped(value, true),
        'goToStep': value['goToStep'],
    };
}

