/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StepAction } from './StepAction';
import {
    StepActionFromJSON,
    StepActionFromJSONTyped,
    StepActionToJSON,
    StepActionToJSONTyped,
} from './StepAction';

/**
 * 
 * @export
 * @interface ChooseWalletAction
 */
export interface ChooseWalletAction extends StepAction {
}

/**
 * Check if a given object implements the ChooseWalletAction interface.
 */
export function instanceOfChooseWalletAction(value: object): value is ChooseWalletAction {
    return true;
}

export function ChooseWalletActionFromJSON(json: any): ChooseWalletAction {
    return ChooseWalletActionFromJSONTyped(json, false);
}

export function ChooseWalletActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChooseWalletAction {
    return json;
}

export function ChooseWalletActionToJSON(json: any): ChooseWalletAction {
    return ChooseWalletActionToJSONTyped(json, false);
}

export function ChooseWalletActionToJSONTyped(value?: ChooseWalletAction | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

