/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CredentialAttributeRequest } from './CredentialAttributeRequest';
import {
    CredentialAttributeRequestFromJSON,
    CredentialAttributeRequestFromJSONTyped,
    CredentialAttributeRequestToJSON,
    CredentialAttributeRequestToJSONTyped,
} from './CredentialAttributeRequest';
import type { IdentifierType } from './IdentifierType';
import {
    IdentifierTypeFromJSON,
    IdentifierTypeFromJSONTyped,
    IdentifierTypeToJSON,
    IdentifierTypeToJSONTyped,
} from './IdentifierType';
import type { Source } from './Source';
import {
    SourceFromJSON,
    SourceFromJSONTyped,
    SourceToJSON,
    SourceToJSONTyped,
} from './Source';

/**
 * 
 * @export
 * @interface CredentialSchemaRequest
 */
export interface CredentialSchemaRequest {
    /**
     * Name of the credential schema
     * @type {string}
     * @memberof CredentialSchemaRequest
     */
    name: string;
    /**
     * Version of the credential schema
     * @type {string}
     * @memberof CredentialSchemaRequest
     */
    version: string;
    /**
     * 
     * @type {IdentifierType}
     * @memberof CredentialSchemaRequest
     */
    identifierType?: IdentifierType;
    /**
     * 
     * @type {Source}
     * @memberof CredentialSchemaRequest
     */
    source?: Source;
    /**
     * External identifier of this schema
     * @type {string}
     * @memberof CredentialSchemaRequest
     */
    identifier?: string;
    /**
     * 
     * @type {Array<CredentialAttributeRequest>}
     * @memberof CredentialSchemaRequest
     */
    attributes?: Array<CredentialAttributeRequest>;
}



/**
 * Check if a given object implements the CredentialSchemaRequest interface.
 */
export function instanceOfCredentialSchemaRequest(value: object): value is CredentialSchemaRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function CredentialSchemaRequestFromJSON(json: any): CredentialSchemaRequest {
    return CredentialSchemaRequestFromJSONTyped(json, false);
}

export function CredentialSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'version': json['version'],
        'identifierType': json['identifierType'] == null ? undefined : IdentifierTypeFromJSON(json['identifierType']),
        'source': json['source'] == null ? undefined : SourceFromJSON(json['source']),
        'identifier': json['identifier'] == null ? undefined : json['identifier'],
        'attributes': json['attributes'] == null ? undefined : ((json['attributes'] as Array<any>).map(CredentialAttributeRequestFromJSON)),
    };
}

export function CredentialSchemaRequestToJSON(json: any): CredentialSchemaRequest {
    return CredentialSchemaRequestToJSONTyped(json, false);
}

export function CredentialSchemaRequestToJSONTyped(value?: CredentialSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'version': value['version'],
        'identifierType': IdentifierTypeToJSON(value['identifierType']),
        'source': SourceToJSON(value['source']),
        'identifier': value['identifier'],
        'attributes': value['attributes'] == null ? undefined : ((value['attributes'] as Array<any>).map(CredentialAttributeRequestToJSON)),
    };
}

