/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Types of credential attributes
 * @export
 */
export const CredentialAttributeType = {
    String: 'STRING',
    Integer: 'INTEGER',
    Float: 'FLOAT',
    Boolean: 'BOOLEAN',
    Date: 'DATE'
} as const;
export type CredentialAttributeType = typeof CredentialAttributeType[keyof typeof CredentialAttributeType];


export function instanceOfCredentialAttributeType(value: any): boolean {
    for (const key in CredentialAttributeType) {
        if (Object.prototype.hasOwnProperty.call(CredentialAttributeType, key)) {
            if (CredentialAttributeType[key as keyof typeof CredentialAttributeType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CredentialAttributeTypeFromJSON(json: any): CredentialAttributeType {
    return CredentialAttributeTypeFromJSONTyped(json, false);
}

export function CredentialAttributeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialAttributeType {
    return json as CredentialAttributeType;
}

export function CredentialAttributeTypeToJSON(value?: CredentialAttributeType | null): any {
    return value as any;
}

export function CredentialAttributeTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CredentialAttributeType {
    return value as CredentialAttributeType;
}

