/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CredentialDefinition } from './CredentialDefinition';
import {
    CredentialDefinitionFromJSON,
    CredentialDefinitionFromJSONTyped,
    CredentialDefinitionToJSON,
    CredentialDefinitionToJSONTyped,
} from './CredentialDefinition';

/**
 * 
 * @export
 * @interface CredentialDefinitionsResponse
 */
export interface CredentialDefinitionsResponse {
    /**
     * List of credential definitions
     * @type {Array<CredentialDefinition>}
     * @memberof CredentialDefinitionsResponse
     */
    credentialDefinitions?: Array<CredentialDefinition>;
}

/**
 * Check if a given object implements the CredentialDefinitionsResponse interface.
 */
export function instanceOfCredentialDefinitionsResponse(value: object): value is CredentialDefinitionsResponse {
    return true;
}

export function CredentialDefinitionsResponseFromJSON(json: any): CredentialDefinitionsResponse {
    return CredentialDefinitionsResponseFromJSONTyped(json, false);
}

export function CredentialDefinitionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialDefinitionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'credentialDefinitions': json['credentialDefinitions'] == null ? undefined : ((json['credentialDefinitions'] as Array<any>).map(CredentialDefinitionFromJSON)),
    };
}

export function CredentialDefinitionsResponseToJSON(json: any): CredentialDefinitionsResponse {
    return CredentialDefinitionsResponseToJSONTyped(json, false);
}

export function CredentialDefinitionsResponseToJSONTyped(value?: CredentialDefinitionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credentialDefinitions': value['credentialDefinitions'] == null ? undefined : ((value['credentialDefinitions'] as Array<any>).map(CredentialDefinitionToJSON)),
    };
}

