/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CredentialSchema } from './CredentialSchema';
import {
    CredentialSchemaFromJSON,
    CredentialSchemaFromJSONTyped,
    CredentialSchemaToJSON,
    CredentialSchemaToJSONTyped,
} from './CredentialSchema';

/**
 * 
 * @export
 * @interface CredentialSchemaResponse
 */
export interface CredentialSchemaResponse {
    /**
     * 
     * @type {CredentialSchema}
     * @memberof CredentialSchemaResponse
     */
    credentialSchema?: CredentialSchema;
}

/**
 * Check if a given object implements the CredentialSchemaResponse interface.
 */
export function instanceOfCredentialSchemaResponse(value: object): value is CredentialSchemaResponse {
    return true;
}

export function CredentialSchemaResponseFromJSON(json: any): CredentialSchemaResponse {
    return CredentialSchemaResponseFromJSONTyped(json, false);
}

export function CredentialSchemaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialSchemaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'credentialSchema': json['credentialSchema'] == null ? undefined : CredentialSchemaFromJSON(json['credentialSchema']),
    };
}

export function CredentialSchemaResponseToJSON(json: any): CredentialSchemaResponse {
    return CredentialSchemaResponseToJSONTyped(json, false);
}

export function CredentialSchemaResponseToJSONTyped(value?: CredentialSchemaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credentialSchema': CredentialSchemaToJSON(value['credentialSchema']),
    };
}

