/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CredentialRepresentation
 */
export interface CredentialRepresentation {
    /**
     * Unique identifier for the credential representation
     * @type {string}
     * @memberof CredentialRepresentation
     */
    id: string;
    /**
     * Date and time the credential representation was created
     * @type {Date}
     * @memberof CredentialRepresentation
     */
    createdAt: Date;
    /**
     * Date and time the credential representation was last updated
     * @type {Date}
     * @memberof CredentialRepresentation
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the CredentialRepresentation interface.
 */
export function instanceOfCredentialRepresentation(value: object): value is CredentialRepresentation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CredentialRepresentationFromJSON(json: any): CredentialRepresentation {
    return CredentialRepresentationFromJSONTyped(json, false);
}

export function CredentialRepresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialRepresentation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function CredentialRepresentationToJSON(json: any): CredentialRepresentation {
    return CredentialRepresentationToJSONTyped(json, false);
}

export function CredentialRepresentationToJSONTyped(value?: CredentialRepresentation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

