/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IssuanceScenario } from './IssuanceScenario';
import {
    IssuanceScenarioFromJSON,
    IssuanceScenarioFromJSONTyped,
    IssuanceScenarioToJSON,
    IssuanceScenarioToJSONTyped,
} from './IssuanceScenario';

/**
 * 
 * @export
 * @interface IssuanceScenarioResponse
 */
export interface IssuanceScenarioResponse {
    /**
     * 
     * @type {IssuanceScenario}
     * @memberof IssuanceScenarioResponse
     */
    issuanceScenario?: IssuanceScenario;
}

/**
 * Check if a given object implements the IssuanceScenarioResponse interface.
 */
export function instanceOfIssuanceScenarioResponse(value: object): value is IssuanceScenarioResponse {
    return true;
}

export function IssuanceScenarioResponseFromJSON(json: any): IssuanceScenarioResponse {
    return IssuanceScenarioResponseFromJSONTyped(json, false);
}

export function IssuanceScenarioResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuanceScenarioResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'issuanceScenario': json['issuanceScenario'] == null ? undefined : IssuanceScenarioFromJSON(json['issuanceScenario']),
    };
}

export function IssuanceScenarioResponseToJSON(json: any): IssuanceScenarioResponse {
    return IssuanceScenarioResponseToJSONTyped(json, false);
}

export function IssuanceScenarioResponseToJSONTyped(value?: IssuanceScenarioResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'issuanceScenario': IssuanceScenarioToJSON(value['issuanceScenario']),
    };
}

