/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IssuanceScenario } from './IssuanceScenario';
import {
    IssuanceScenarioFromJSON,
    IssuanceScenarioFromJSONTyped,
    IssuanceScenarioToJSON,
    IssuanceScenarioToJSONTyped,
} from './IssuanceScenario';

/**
 * 
 * @export
 * @interface IssuanceScenariosResponse
 */
export interface IssuanceScenariosResponse {
    /**
     * 
     * @type {Array<IssuanceScenario>}
     * @memberof IssuanceScenariosResponse
     */
    issuanceScenarios?: Array<IssuanceScenario>;
}

/**
 * Check if a given object implements the IssuanceScenariosResponse interface.
 */
export function instanceOfIssuanceScenariosResponse(value: object): value is IssuanceScenariosResponse {
    return true;
}

export function IssuanceScenariosResponseFromJSON(json: any): IssuanceScenariosResponse {
    return IssuanceScenariosResponseFromJSONTyped(json, false);
}

export function IssuanceScenariosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuanceScenariosResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'issuanceScenarios': json['issuanceScenarios'] == null ? undefined : ((json['issuanceScenarios'] as Array<any>).map(IssuanceScenarioFromJSON)),
    };
}

export function IssuanceScenariosResponseToJSON(json: any): IssuanceScenariosResponse {
    return IssuanceScenariosResponseToJSONTyped(json, false);
}

export function IssuanceScenariosResponseToJSONTyped(value?: IssuanceScenariosResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'issuanceScenarios': value['issuanceScenarios'] == null ? undefined : ((value['issuanceScenarios'] as Array<any>).map(IssuanceScenarioToJSON)),
    };
}

