/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListIssuanceScenarios400Response
 */
export interface ListIssuanceScenarios400Response {
    /**
     * 
     * @type {string}
     * @memberof ListIssuanceScenarios400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the ListIssuanceScenarios400Response interface.
 */
export function instanceOfListIssuanceScenarios400Response(value: object): value is ListIssuanceScenarios400Response {
    return true;
}

export function ListIssuanceScenarios400ResponseFromJSON(json: any): ListIssuanceScenarios400Response {
    return ListIssuanceScenarios400ResponseFromJSONTyped(json, false);
}

export function ListIssuanceScenarios400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListIssuanceScenarios400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ListIssuanceScenarios400ResponseToJSON(json: any): ListIssuanceScenarios400Response {
    return ListIssuanceScenarios400ResponseToJSONTyped(json, false);
}

export function ListIssuanceScenarios400ResponseToJSONTyped(value?: ListIssuanceScenarios400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

