/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Persona } from './Persona';
import {
    PersonaFromJSON,
    PersonaFromJSONTyped,
    PersonaToJSON,
    PersonaToJSONTyped,
} from './Persona';

/**
 * 
 * @export
 * @interface PersonasResponse
 */
export interface PersonasResponse {
    /**
     * 
     * @type {Array<Persona>}
     * @memberof PersonasResponse
     */
    personas?: Array<Persona>;
}

/**
 * Check if a given object implements the PersonasResponse interface.
 */
export function instanceOfPersonasResponse(value: object): value is PersonasResponse {
    return true;
}

export function PersonasResponseFromJSON(json: any): PersonasResponse {
    return PersonasResponseFromJSONTyped(json, false);
}

export function PersonasResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonasResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'personas': json['personas'] == null ? undefined : ((json['personas'] as Array<any>).map(PersonaFromJSON)),
    };
}

export function PersonasResponseToJSON(json: any): PersonasResponse {
    return PersonasResponseToJSONTyped(json, false);
}

export function PersonasResponseToJSONTyped(value?: PersonasResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'personas': value['personas'] == null ? undefined : ((value['personas'] as Array<any>).map(PersonaToJSON)),
    };
}

