/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Persona } from './Persona';
import {
    PersonaFromJSON,
    PersonaFromJSONTyped,
    PersonaToJSON,
    PersonaToJSONTyped,
} from './Persona';

/**
 * 
 * @export
 * @interface PersonaResponse
 */
export interface PersonaResponse {
    /**
     * 
     * @type {Persona}
     * @memberof PersonaResponse
     */
    persona?: Persona;
}

/**
 * Check if a given object implements the PersonaResponse interface.
 */
export function instanceOfPersonaResponse(value: object): value is PersonaResponse {
    return true;
}

export function PersonaResponseFromJSON(json: any): PersonaResponse {
    return PersonaResponseFromJSONTyped(json, false);
}

export function PersonaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'persona': json['persona'] == null ? undefined : PersonaFromJSON(json['persona']),
    };
}

export function PersonaResponseToJSON(json: any): PersonaResponse {
    return PersonaResponseToJSONTyped(json, false);
}

export function PersonaResponseToJSONTyped(value?: PersonaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'persona': PersonaToJSON(value['persona']),
    };
}

