/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PresentationScenario } from './PresentationScenario';
import {
    PresentationScenarioFromJSON,
    PresentationScenarioFromJSONTyped,
    PresentationScenarioToJSON,
    PresentationScenarioToJSONTyped,
} from './PresentationScenario';

/**
 * 
 * @export
 * @interface PresentationScenariosResponse
 */
export interface PresentationScenariosResponse {
    /**
     * 
     * @type {Array<PresentationScenario>}
     * @memberof PresentationScenariosResponse
     */
    presentationScenarios?: Array<PresentationScenario>;
}

/**
 * Check if a given object implements the PresentationScenariosResponse interface.
 */
export function instanceOfPresentationScenariosResponse(value: object): value is PresentationScenariosResponse {
    return true;
}

export function PresentationScenariosResponseFromJSON(json: any): PresentationScenariosResponse {
    return PresentationScenariosResponseFromJSONTyped(json, false);
}

export function PresentationScenariosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresentationScenariosResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'presentationScenarios': json['presentationScenarios'] == null ? undefined : ((json['presentationScenarios'] as Array<any>).map(PresentationScenarioFromJSON)),
    };
}

export function PresentationScenariosResponseToJSON(json: any): PresentationScenariosResponse {
    return PresentationScenariosResponseToJSONTyped(json, false);
}

export function PresentationScenariosResponseToJSONTyped(value?: PresentationScenariosResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'presentationScenarios': value['presentationScenarios'] == null ? undefined : ((value['presentationScenarios'] as Array<any>).map(PresentationScenarioToJSON)),
    };
}

