/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PresentationScenario } from './PresentationScenario';
import {
    PresentationScenarioFromJSON,
    PresentationScenarioFromJSONTyped,
    PresentationScenarioToJSON,
    PresentationScenarioToJSONTyped,
} from './PresentationScenario';

/**
 * 
 * @export
 * @interface PresentationScenarioResponse
 */
export interface PresentationScenarioResponse {
    /**
     * 
     * @type {PresentationScenario}
     * @memberof PresentationScenarioResponse
     */
    presentationScenario?: PresentationScenario;
}

/**
 * Check if a given object implements the PresentationScenarioResponse interface.
 */
export function instanceOfPresentationScenarioResponse(value: object): value is PresentationScenarioResponse {
    return true;
}

export function PresentationScenarioResponseFromJSON(json: any): PresentationScenarioResponse {
    return PresentationScenarioResponseFromJSONTyped(json, false);
}

export function PresentationScenarioResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresentationScenarioResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'presentationScenario': json['presentationScenario'] == null ? undefined : PresentationScenarioFromJSON(json['presentationScenario']),
    };
}

export function PresentationScenarioResponseToJSON(json: any): PresentationScenarioResponse {
    return PresentationScenarioResponseToJSONTyped(json, false);
}

export function PresentationScenarioResponseToJSONTyped(value?: PresentationScenarioResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'presentationScenario': PresentationScenarioToJSON(value['presentationScenario']),
    };
}

