/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Types of supported relying parties
 * @export
 */
export const RelyingPartyType = {
    Aries: 'ARIES'
} as const;
export type RelyingPartyType = typeof RelyingPartyType[keyof typeof RelyingPartyType];


export function instanceOfRelyingPartyType(value: any): boolean {
    for (const key in RelyingPartyType) {
        if (Object.prototype.hasOwnProperty.call(RelyingPartyType, key)) {
            if (RelyingPartyType[key as keyof typeof RelyingPartyType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RelyingPartyTypeFromJSON(json: any): RelyingPartyType {
    return RelyingPartyTypeFromJSONTyped(json, false);
}

export function RelyingPartyTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelyingPartyType {
    return json as RelyingPartyType;
}

export function RelyingPartyTypeToJSON(value?: RelyingPartyType | null): any {
    return value as any;
}

export function RelyingPartyTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): RelyingPartyType {
    return value as RelyingPartyType;
}

