/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RelyingParty } from './RelyingParty';
import {
    RelyingPartyFromJSON,
    RelyingPartyFromJSONTyped,
    RelyingPartyToJSON,
    RelyingPartyToJSONTyped,
} from './RelyingParty';

/**
 * 
 * @export
 * @interface RelyingPartyResponse
 */
export interface RelyingPartyResponse {
    /**
     * 
     * @type {RelyingParty}
     * @memberof RelyingPartyResponse
     */
    relyingParty?: RelyingParty;
}

/**
 * Check if a given object implements the RelyingPartyResponse interface.
 */
export function instanceOfRelyingPartyResponse(value: object): value is RelyingPartyResponse {
    return true;
}

export function RelyingPartyResponseFromJSON(json: any): RelyingPartyResponse {
    return RelyingPartyResponseFromJSONTyped(json, false);
}

export function RelyingPartyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelyingPartyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'relyingParty': json['relyingParty'] == null ? undefined : RelyingPartyFromJSON(json['relyingParty']),
    };
}

export function RelyingPartyResponseToJSON(json: any): RelyingPartyResponse {
    return RelyingPartyResponseToJSONTyped(json, false);
}

export function RelyingPartyResponseToJSONTyped(value?: RelyingPartyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'relyingParty': RelyingPartyToJSON(value['relyingParty']),
    };
}

