/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CredentialDefinition } from './CredentialDefinition';
import {
    CredentialDefinitionFromJSON,
    CredentialDefinitionFromJSONTyped,
    CredentialDefinitionToJSON,
    CredentialDefinitionToJSONTyped,
} from './CredentialDefinition';
import type { Asset } from './Asset';
import {
    AssetFromJSON,
    AssetFromJSONTyped,
    AssetToJSON,
    AssetToJSONTyped,
} from './Asset';
import type { RelyingPartyType } from './RelyingPartyType';
import {
    RelyingPartyTypeFromJSON,
    RelyingPartyTypeFromJSONTyped,
    RelyingPartyTypeToJSON,
    RelyingPartyTypeToJSONTyped,
} from './RelyingPartyType';

/**
 * 
 * @export
 * @interface RelyingParty
 */
export interface RelyingParty {
    /**
     * Unique identifier for the relying party
     * @type {string}
     * @memberof RelyingParty
     */
    id: string;
    /**
     * Name of the relying party
     * @type {string}
     * @memberof RelyingParty
     */
    name: string;
    /**
     * Detailed description of the relying party
     * @type {string}
     * @memberof RelyingParty
     */
    description: string;
    /**
     * 
     * @type {RelyingPartyType}
     * @memberof RelyingParty
     */
    type: RelyingPartyType;
    /**
     * Organization the relying party belongs to
     * @type {string}
     * @memberof RelyingParty
     */
    organization?: string;
    /**
     * 
     * @type {Asset}
     * @memberof RelyingParty
     */
    logo?: Asset;
    /**
     * 
     * @type {Array<CredentialDefinition>}
     * @memberof RelyingParty
     */
    credentialDefinitions: Array<CredentialDefinition>;
    /**
     * Date and time the relying party was created
     * @type {Date}
     * @memberof RelyingParty
     */
    createdAt: Date;
    /**
     * Date and time the relying party was last updated
     * @type {Date}
     * @memberof RelyingParty
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the RelyingParty interface.
 */
export function instanceOfRelyingParty(value: object): value is RelyingParty {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('credentialDefinitions' in value) || value['credentialDefinitions'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function RelyingPartyFromJSON(json: any): RelyingParty {
    return RelyingPartyFromJSONTyped(json, false);
}

export function RelyingPartyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelyingParty {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'type': RelyingPartyTypeFromJSON(json['type']),
        'organization': json['organization'] == null ? undefined : json['organization'],
        'logo': json['logo'] == null ? undefined : AssetFromJSON(json['logo']),
        'credentialDefinitions': ((json['credentialDefinitions'] as Array<any>).map(CredentialDefinitionFromJSON)),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function RelyingPartyToJSON(json: any): RelyingParty {
    return RelyingPartyToJSONTyped(json, false);
}

export function RelyingPartyToJSONTyped(value?: RelyingParty | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'type': RelyingPartyTypeToJSON(value['type']),
        'organization': value['organization'],
        'logo': AssetToJSON(value['logo']),
        'credentialDefinitions': ((value['credentialDefinitions'] as Array<any>).map(CredentialDefinitionToJSON)),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

