/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Types of supported scenarios
 * @export
 */
export const ScenarioType = {
    Issuance: 'ISSUANCE',
    Presentation: 'PRESENTATION'
} as const;
export type ScenarioType = typeof ScenarioType[keyof typeof ScenarioType];


export function instanceOfScenarioType(value: any): boolean {
    for (const key in ScenarioType) {
        if (Object.prototype.hasOwnProperty.call(ScenarioType, key)) {
            if (ScenarioType[key as keyof typeof ScenarioType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ScenarioTypeFromJSON(json: any): ScenarioType {
    return ScenarioTypeFromJSONTyped(json, false);
}

export function ScenarioTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScenarioType {
    return json as ScenarioType;
}

export function ScenarioTypeToJSON(value?: ScenarioType | null): any {
    return value as any;
}

export function ScenarioTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ScenarioType {
    return value as ScenarioType;
}

