/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StepAction } from './StepAction';
import {
    StepActionFromJSON,
    StepActionFromJSONTyped,
    StepActionToJSON,
    StepActionToJSONTyped,
} from './StepAction';

/**
 * 
 * @export
 * @interface SetupConnectionAction
 */
export interface SetupConnectionAction extends StepAction {
}

/**
 * Check if a given object implements the SetupConnectionAction interface.
 */
export function instanceOfSetupConnectionAction(value: object): value is SetupConnectionAction {
    return true;
}

export function SetupConnectionActionFromJSON(json: any): SetupConnectionAction {
    return SetupConnectionActionFromJSONTyped(json, false);
}

export function SetupConnectionActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupConnectionAction {
    return json;
}

export function SetupConnectionActionToJSON(json: any): SetupConnectionAction {
    return SetupConnectionActionToJSONTyped(json, false);
}

export function SetupConnectionActionToJSONTyped(value?: SetupConnectionAction | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

