/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Showcase } from './Showcase';
import {
    ShowcaseFromJSON,
    ShowcaseFromJSONTyped,
    ShowcaseToJSON,
    ShowcaseToJSONTyped,
} from './Showcase';

/**
 * 
 * @export
 * @interface ShowcaseResponse
 */
export interface ShowcaseResponse {
    /**
     * 
     * @type {Showcase}
     * @memberof ShowcaseResponse
     */
    showcase?: Showcase;
}

/**
 * Check if a given object implements the ShowcaseResponse interface.
 */
export function instanceOfShowcaseResponse(value: object): value is ShowcaseResponse {
    return true;
}

export function ShowcaseResponseFromJSON(json: any): ShowcaseResponse {
    return ShowcaseResponseFromJSONTyped(json, false);
}

export function ShowcaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowcaseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'showcase': json['showcase'] == null ? undefined : ShowcaseFromJSON(json['showcase']),
    };
}

export function ShowcaseResponseToJSON(json: any): ShowcaseResponse {
    return ShowcaseResponseToJSONTyped(json, false);
}

export function ShowcaseResponseToJSONTyped(value?: ShowcaseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'showcase': ShowcaseToJSON(value['showcase']),
    };
}

