/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Showcase } from './Showcase';
import {
    ShowcaseFromJSON,
    ShowcaseFromJSONTyped,
    ShowcaseToJSON,
    ShowcaseToJSONTyped,
} from './Showcase';

/**
 * 
 * @export
 * @interface ShowcasesResponse
 */
export interface ShowcasesResponse {
    /**
     * List of showcases
     * @type {Array<Showcase>}
     * @memberof ShowcasesResponse
     */
    showcases?: Array<Showcase>;
}

/**
 * Check if a given object implements the ShowcasesResponse interface.
 */
export function instanceOfShowcasesResponse(value: object): value is ShowcasesResponse {
    return true;
}

export function ShowcasesResponseFromJSON(json: any): ShowcasesResponse {
    return ShowcasesResponseFromJSONTyped(json, false);
}

export function ShowcasesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowcasesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'showcases': json['showcases'] == null ? undefined : ((json['showcases'] as Array<any>).map(ShowcaseFromJSON)),
    };
}

export function ShowcasesResponseToJSON(json: any): ShowcasesResponse {
    return ShowcasesResponseToJSONTyped(json, false);
}

export function ShowcasesResponseToJSONTyped(value?: ShowcasesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'showcases': value['showcases'] == null ? undefined : ((value['showcases'] as Array<any>).map(ShowcaseToJSON)),
    };
}

