/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StepAction } from './StepAction';
import {
    StepActionFromJSON,
    StepActionFromJSONTyped,
    StepActionToJSON,
    StepActionToJSONTyped,
} from './StepAction';

/**
 * 
 * @export
 * @interface StepActionsResponse
 */
export interface StepActionsResponse {
    /**
     * 
     * @type {Array<StepAction>}
     * @memberof StepActionsResponse
     */
    actions?: Array<StepAction>;
}

/**
 * Check if a given object implements the StepActionsResponse interface.
 */
export function instanceOfStepActionsResponse(value: object): value is StepActionsResponse {
    return true;
}

export function StepActionsResponseFromJSON(json: any): StepActionsResponse {
    return StepActionsResponseFromJSONTyped(json, false);
}

export function StepActionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepActionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'actions': json['actions'] == null ? undefined : ((json['actions'] as Array<any>).map(StepActionFromJSON)),
    };
}

export function StepActionsResponseToJSON(json: any): StepActionsResponse {
    return StepActionsResponseToJSONTyped(json, false);
}

export function StepActionsResponseToJSONTyped(value?: StepActionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actions': value['actions'] == null ? undefined : ((value['actions'] as Array<any>).map(StepActionToJSON)),
    };
}

