/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AriesOOBActionRequest } from './AriesOOBActionRequest';
import {
    instanceOfAriesOOBActionRequest,
    AriesOOBActionRequestFromJSON,
    AriesOOBActionRequestFromJSONTyped,
    AriesOOBActionRequestToJSON,
} from './AriesOOBActionRequest';

/**
 * @type StepRequestActionsInner
 * 
 * @export
 */
export type StepRequestActionsInner = AriesOOBActionRequest;

export function StepRequestActionsInnerFromJSON(json: any): StepRequestActionsInner {
    return StepRequestActionsInnerFromJSONTyped(json, false);
}

export function StepRequestActionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepRequestActionsInner {
    if (json == null) {
        return json;
    }
    if (instanceOfAriesOOBActionRequest(json)) {
        return AriesOOBActionRequestFromJSONTyped(json, true);
    }

    return {} as any;
}

export function StepRequestActionsInnerToJSON(json: any): any {
    return StepRequestActionsInnerToJSONTyped(json, false);
}

export function StepRequestActionsInnerToJSONTyped(value?: StepRequestActionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfAriesOOBActionRequest(value)) {
        return AriesOOBActionRequestToJSON(value as AriesOOBActionRequest);
    }

    return {};
}

