/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Step } from './Step';
import {
    StepFromJSON,
    StepFromJSONTyped,
    StepToJSON,
    StepToJSONTyped,
} from './Step';

/**
 * 
 * @export
 * @interface StepResponse
 */
export interface StepResponse {
    /**
     * 
     * @type {Step}
     * @memberof StepResponse
     */
    step?: Step;
}

/**
 * Check if a given object implements the StepResponse interface.
 */
export function instanceOfStepResponse(value: object): value is StepResponse {
    return true;
}

export function StepResponseFromJSON(json: any): StepResponse {
    return StepResponseFromJSONTyped(json, false);
}

export function StepResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'step': json['step'] == null ? undefined : StepFromJSON(json['step']),
    };
}

export function StepResponseToJSON(json: any): StepResponse {
    return StepResponseToJSONTyped(json, false);
}

export function StepResponseToJSONTyped(value?: StepResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'step': StepToJSON(value['step']),
    };
}

