/* tslint:disable */
/* eslint-disable */
/**
 * BC Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import { AriesOOBActionRequest, AriesOOBActionRequestFromJSONTyped, AriesOOBActionRequestToJSON, AriesOOBActionRequestToJSONTyped } from './AriesOOBActionRequest';
/**
 * 
 * @export
 * @interface StepActionRequest
 */
export interface StepActionRequest {
    /**
     * Title of the action
     * @type {string}
     * @memberof StepActionRequest
     */
    title: string;
    /**
     * Descriptive text for the action
     * @type {string}
     * @memberof StepActionRequest
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof StepActionRequest
     */
    actionType: string;
}

/**
 * Check if a given object implements the StepActionRequest interface.
 */
export function instanceOfStepActionRequest(value: object): value is StepActionRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('actionType' in value) || value['actionType'] === undefined) return false;
    return true;
}

export function StepActionRequestFromJSON(json: any): StepActionRequest {
    return StepActionRequestFromJSONTyped(json, false);
}

export function StepActionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepActionRequest {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['actionType'] === 'ARIES_OOB') {
            return AriesOOBActionRequestFromJSONTyped(json, ignoreDiscriminator);
        }
    }
    return {
        
        'title': json['title'],
        'text': json['text'],
        'actionType': json['actionType'],
    };
}

export function StepActionRequestToJSON(json: any): StepActionRequest {
    return StepActionRequestToJSONTyped(json, false);
}

export function StepActionRequestToJSONTyped(value?: StepActionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (!ignoreDiscriminator) {
        switch (value['actionType']) {
            case 'ARIES_OOB':
                return AriesOOBActionRequestToJSONTyped(value as AriesOOBActionRequest, ignoreDiscriminator);
            default:
                throw new Error(`No variant of StepActionRequest exists with 'actionType=${value['actionType']}'`);
        }
    }

    return {
        
        'title': value['title'],
        'text': value['text'],
        'actionType': value['actionType'],
    };
}

