#!/bin/bash

source ./setup-env.sh

# Push API server image
docker tag ${API_SERVER_IMAGE}:latest ${DOCKER_REGISTRY}/${TAGGED_API_SERVER_IMAGE}:${PACKAGE_VERSION}
docker push ${DOCKER_REGISTRY}/${TAGGED_API_SERVER_IMAGE}:${PACKAGE_VERSION}
docker tag ${API_SERVER_IMAGE}:latest ${DOCKER_REGISTRY}/${TAGGED_API_SERVER_IMAGE}:latest
docker push ${DOCKER_REGISTRY}/${TAGGED_API_SERVER_IMAGE}:latest

# Push tract adapter image
docker tag ${TRACTION_ADAPTER_IMAGE}:latest ${DOCKER_REGISTRY}/${TAGGED_TRACTION_ADAPTER_IMAGE}:${PACKAGE_VERSION}
docker push ${DOCKER_REGISTRY}/${TAGGED_TRACTION_ADAPTER_IMAGE}:${PACKAGE_VERSION}
docker tag ${TRACTION_ADAPTER_IMAGE}:latest ${DOCKER_REGISTRY}/${TAGGED_TRACTION_ADAPTER_IMAGE}:latest
docker push ${DOCKER_REGISTRY}/${TAGGED_TRACTION_ADAPTER_IMAGE}:latest
