'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAriesProofRequestRequest = instanceOfAriesProofRequestRequest;
exports.AriesProofRequestRequestFromJSON = AriesProofRequestRequestFromJSON;
exports.AriesProofRequestRequestFromJSONTyped = AriesProofRequestRequestFromJSONTyped;
exports.AriesProofRequestRequestToJSON = AriesProofRequestRequestToJSON;
exports.AriesProofRequestRequestToJSONTyped = AriesProofRequestRequestToJSONTyped;
const runtime_1 = require("../runtime");
const AriesRequestCredentialAttributes_1 = require("./AriesRequestCredentialAttributes");
const AriesRequestCredentialPredicates_1 = require("./AriesRequestCredentialPredicates");
/**
 * Check if a given object implements the AriesProofRequestRequest interface.
 */
function instanceOfAriesProofRequestRequest(value) {
    if (!('attributes' in value) || value['attributes'] === undefined)
        return false;
    if (!('predicates' in value) || value['predicates'] === undefined)
        return false;
    return true;
}
function AriesProofRequestRequestFromJSON(json) {
    return AriesProofRequestRequestFromJSONTyped(json, false);
}
function AriesProofRequestRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'attributes': ((0, runtime_1.mapValues)(json['attributes'], AriesRequestCredentialAttributes_1.AriesRequestCredentialAttributesFromJSON)),
        'predicates': ((0, runtime_1.mapValues)(json['predicates'], AriesRequestCredentialPredicates_1.AriesRequestCredentialPredicatesFromJSON)),
    };
}
function AriesProofRequestRequestToJSON(json) {
    return AriesProofRequestRequestToJSONTyped(json, false);
}
function AriesProofRequestRequestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'attributes': ((0, runtime_1.mapValues)(value['attributes'], AriesRequestCredentialAttributes_1.AriesRequestCredentialAttributesToJSON)),
        'predicates': ((0, runtime_1.mapValues)(value['predicates'], AriesRequestCredentialPredicates_1.AriesRequestCredentialPredicatesToJSON)),
    };
}
//# sourceMappingURL=AriesProofRequestRequest.js.map