'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAssetRequest = instanceOfAssetRequest;
exports.AssetRequestFromJSON = AssetRequestFromJSON;
exports.AssetRequestFromJSONTyped = AssetRequestFromJSONTyped;
exports.AssetRequestToJSON = AssetRequestToJSON;
exports.AssetRequestToJSONTyped = AssetRequestToJSONTyped;
/**
 * Check if a given object implements the AssetRequest interface.
 */
function instanceOfAssetRequest(value) {
    if (!('mediaType' in value) || value['mediaType'] === undefined)
        return false;
    if (!('content' in value) || value['content'] === undefined)
        return false;
    return true;
}
function AssetRequestFromJSON(json) {
    return AssetRequestFromJSONTyped(json, false);
}
function AssetRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'mediaType': json['mediaType'],
        'content': json['content'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}
function AssetRequestToJSON(json) {
    return AssetRequestToJSONTyped(json, false);
}
function AssetRequestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'mediaType': value['mediaType'],
        'content': value['content'],
        'fileName': value['fileName'],
        'description': value['description'],
    };
}
//# sourceMappingURL=AssetRequest.js.map