'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAssetResponse = instanceOfAssetResponse;
exports.AssetResponseFromJSON = AssetResponseFromJSON;
exports.AssetResponseFromJSONTyped = AssetResponseFromJSONTyped;
exports.AssetResponseToJSON = AssetResponseToJSON;
exports.AssetResponseToJSONTyped = AssetResponseToJSONTyped;
const Asset_1 = require("./Asset");
/**
 * Check if a given object implements the AssetResponse interface.
 */
function instanceOfAssetResponse(value) {
    if (!('asset' in value) || value['asset'] === undefined)
        return false;
    return true;
}
function AssetResponseFromJSON(json) {
    return AssetResponseFromJSONTyped(json, false);
}
function AssetResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'asset': (0, Asset_1.AssetFromJSON)(json['asset']),
    };
}
function AssetResponseToJSON(json) {
    return AssetResponseToJSONTyped(json, false);
}
function AssetResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'asset': (0, Asset_1.AssetToJSON)(value['asset']),
    };
}
//# sourceMappingURL=AssetResponse.js.map