'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfCredentialSchemaResponse = instanceOfCredentialSchemaResponse;
exports.CredentialSchemaResponseFromJSON = CredentialSchemaResponseFromJSON;
exports.CredentialSchemaResponseFromJSONTyped = CredentialSchemaResponseFromJSONTyped;
exports.CredentialSchemaResponseToJSON = CredentialSchemaResponseToJSON;
exports.CredentialSchemaResponseToJSONTyped = CredentialSchemaResponseToJSONTyped;
const CredentialSchema_1 = require("./CredentialSchema");
/**
 * Check if a given object implements the CredentialSchemaResponse interface.
 */
function instanceOfCredentialSchemaResponse(value) {
    return true;
}
function CredentialSchemaResponseFromJSON(json) {
    return CredentialSchemaResponseFromJSONTyped(json, false);
}
function CredentialSchemaResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'credentialSchema': json['credentialSchema'] == null ? undefined : (0, CredentialSchema_1.CredentialSchemaFromJSON)(json['credentialSchema']),
    };
}
function CredentialSchemaResponseToJSON(json) {
    return CredentialSchemaResponseToJSONTyped(json, false);
}
function CredentialSchemaResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'credentialSchema': (0, CredentialSchema_1.CredentialSchemaToJSON)(value['credentialSchema']),
    };
}
//# sourceMappingURL=CredentialSchemaResponse.js.map