'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CredentialDefinitionRequestRevocationFromJSON = CredentialDefinitionRequestRevocationFromJSON;
exports.CredentialDefinitionRequestRevocationFromJSONTyped = CredentialDefinitionRequestRevocationFromJSONTyped;
exports.CredentialDefinitionRequestRevocationToJSON = CredentialDefinitionRequestRevocationToJSON;
exports.CredentialDefinitionRequestRevocationToJSONTyped = CredentialDefinitionRequestRevocationToJSONTyped;
const AnonCredRevocation_1 = require("./AnonCredRevocation");
const RevocationInfo_1 = require("./RevocationInfo");
function CredentialDefinitionRequestRevocationFromJSON(json) {
    return CredentialDefinitionRequestRevocationFromJSONTyped(json, false);
}
function CredentialDefinitionRequestRevocationFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    if ((0, AnonCredRevocation_1.instanceOfAnonCredRevocation)(json)) {
        return (0, AnonCredRevocation_1.AnonCredRevocationFromJSONTyped)(json, true);
    }
    if ((0, RevocationInfo_1.instanceOfRevocationInfo)(json)) {
        return (0, RevocationInfo_1.RevocationInfoFromJSONTyped)(json, true);
    }
    return {};
}
function CredentialDefinitionRequestRevocationToJSON(json) {
    return CredentialDefinitionRequestRevocationToJSONTyped(json, false);
}
function CredentialDefinitionRequestRevocationToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    if ((0, AnonCredRevocation_1.instanceOfAnonCredRevocation)(value)) {
        return (0, AnonCredRevocation_1.AnonCredRevocationToJSON)(value);
    }
    if ((0, RevocationInfo_1.instanceOfRevocationInfo)(value)) {
        return (0, RevocationInfo_1.RevocationInfoToJSON)(value);
    }
    return {};
}
//# sourceMappingURL=CredentialDefinitionRequestRevocation.js.map