'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IdentifierType = void 0;
exports.instanceOfIdentifierType = instanceOfIdentifierType;
exports.IdentifierTypeFromJSON = IdentifierTypeFromJSON;
exports.IdentifierTypeFromJSONTyped = IdentifierTypeFromJSONTyped;
exports.IdentifierTypeToJSON = IdentifierTypeToJSON;
exports.IdentifierTypeToJSONTyped = IdentifierTypeToJSONTyped;
/**
 * Types of supported identifiers
 * @export
 */
exports.IdentifierType = {
    Did: 'DID'
};
function instanceOfIdentifierType(value) {
    for (const key in exports.IdentifierType) {
        if (Object.prototype.hasOwnProperty.call(exports.IdentifierType, key)) {
            if (exports.IdentifierType[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function IdentifierTypeFromJSON(json) {
    return IdentifierTypeFromJSONTyped(json, false);
}
function IdentifierTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function IdentifierTypeToJSON(value) {
    return value;
}
function IdentifierTypeToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
//# sourceMappingURL=IdentifierType.js.map