/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { IdentifierType } from '../../src/models/IdentifierType'
import type { IssuerType } from '../../src/models/IssuerType'

/**
 *
 * @export
 * @interface IssuerRequest
 */
export interface IssuerRequest {
  /**
   * Name of the issuer
   * @type {string}
   * @memberof IssuerRequest
   */
  name: string
  /**
   * Detailed description of the issuer
   * @type {string}
   * @memberof IssuerRequest
   */
  description: string
  /**
   *
   * @type {IssuerType}
   * @memberof IssuerRequest
   */
  type: IssuerType
  /**
   *
   * @type {IdentifierType}
   * @memberof IssuerRequest
   */
  identifierType?: IdentifierType
  /**
   * External identifier of this issuer
   * @type {string}
   * @memberof IssuerRequest
   */
  identifier?: string
  /**
   * Organization the issuer belongs to
   * @type {string}
   * @memberof IssuerRequest
   */
  organization?: string
  /**
   *
   * @type {string}
   * @memberof IssuerRequest
   */
  logo?: string
  /**
   *
   * @type {Array<string>}
   * @memberof IssuerRequest
   */
  credentialDefinitions: Array<string>
  /**
   *
   * @type {Array<string>}
   * @memberof IssuerRequest
   */
  credentialSchemas: Array<string>
}
/**
 * Check if a given object implements the IssuerRequest interface.
 */
export declare function instanceOfIssuerRequest(value: object): value is IssuerRequest
export declare function IssuerRequestFromJSON(json: any): IssuerRequest
export declare function IssuerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuerRequest
export declare function IssuerRequestToJSON(json: any): IssuerRequest
export declare function IssuerRequestToJSONTyped(value?: IssuerRequest | null, ignoreDiscriminator?: boolean): any
//# sourceMappingURL=IssuerRequest.d.ts.map
