'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfIssuanceFlowRequest = instanceOfIssuanceFlowRequest;
exports.IssuanceFlowRequestFromJSON = IssuanceFlowRequestFromJSON;
exports.IssuanceFlowRequestFromJSONTyped = IssuanceFlowRequestFromJSONTyped;
exports.IssuanceFlowRequestToJSON = IssuanceFlowRequestToJSON;
exports.IssuanceFlowRequestToJSONTyped = IssuanceFlowRequestToJSONTyped;
const StepRequest_1 = require("./StepRequest");
/**
 * Check if a given object implements the IssuanceFlowRequest interface.
 */
function instanceOfIssuanceFlowRequest(value) {
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('description' in value) || value['description'] === undefined)
        return false;
    if (!('issuer' in value) || value['issuer'] === undefined)
        return false;
    return true;
}
function IssuanceFlowRequestFromJSON(json) {
    return IssuanceFlowRequestFromJSONTyped(json, false);
}
function IssuanceFlowRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'],
        'description': json['description'],
        'steps': json['steps'] == null ? undefined : (json['steps'].map(StepRequest_1.StepRequestFromJSON)),
        'personas': json['personas'] == null ? undefined : json['personas'],
        'issuer': json['issuer'],
    };
}
function IssuanceFlowRequestToJSON(json) {
    return IssuanceFlowRequestToJSONTyped(json, false);
}
function IssuanceFlowRequestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'description': value['description'],
        'steps': value['steps'] == null ? undefined : (value['steps'].map(StepRequest_1.StepRequestToJSON)),
        'personas': value['personas'],
        'issuer': value['issuer'],
    };
}
//# sourceMappingURL=IssuanceFlowRequest.js.map