'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListCredentialRepresentations200ResponseInnerFromJSON = ListCredentialRepresentations200ResponseInnerFromJSON;
exports.ListCredentialRepresentations200ResponseInnerFromJSONTyped = ListCredentialRepresentations200ResponseInnerFromJSONTyped;
exports.ListCredentialRepresentations200ResponseInnerToJSON = ListCredentialRepresentations200ResponseInnerToJSON;
exports.ListCredentialRepresentations200ResponseInnerToJSONTyped = ListCredentialRepresentations200ResponseInnerToJSONTyped;
const CredentialRepresentation_1 = require("./CredentialRepresentation");
const OCARepresentation_1 = require("./OCARepresentation");
function ListCredentialRepresentations200ResponseInnerFromJSON(json) {
    return ListCredentialRepresentations200ResponseInnerFromJSONTyped(json, false);
}
function ListCredentialRepresentations200ResponseInnerFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    if ((0, CredentialRepresentation_1.instanceOfCredentialRepresentation)(json)) {
        return (0, CredentialRepresentation_1.CredentialRepresentationFromJSONTyped)(json, true);
    }
    if ((0, OCARepresentation_1.instanceOfOCARepresentation)(json)) {
        return (0, OCARepresentation_1.OCARepresentationFromJSONTyped)(json, true);
    }
    return {};
}
function ListCredentialRepresentations200ResponseInnerToJSON(json) {
    return ListCredentialRepresentations200ResponseInnerToJSONTyped(json, false);
}
function ListCredentialRepresentations200ResponseInnerToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    if ((0, CredentialRepresentation_1.instanceOfCredentialRepresentation)(value)) {
        return (0, CredentialRepresentation_1.CredentialRepresentationToJSON)(value);
    }
    if ((0, OCARepresentation_1.instanceOfOCARepresentation)(value)) {
        return (0, OCARepresentation_1.OCARepresentationToJSON)(value);
    }
    return {};
}
//# sourceMappingURL=ListCredentialRepresentations200ResponseInner.js.map