/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CredentialRepresentation } from '../../src/models/CredentialRepresentation'
import type { OCARepresentation } from '../../src/models/OCARepresentation'

/**
 * @type ListCredentialRepresentations200ResponseInner
 *
 * @export
 */
export type ListCredentialRepresentations200ResponseInner = CredentialRepresentation | OCARepresentation
export declare function ListCredentialRepresentations200ResponseInnerFromJSON(
  json: any
): ListCredentialRepresentations200ResponseInner
export declare function ListCredentialRepresentations200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListCredentialRepresentations200ResponseInner
export declare function ListCredentialRepresentations200ResponseInnerToJSON(json: any): any
export declare function ListCredentialRepresentations200ResponseInnerToJSONTyped(
  value?: ListCredentialRepresentations200ResponseInner | null,
  ignoreDiscriminator?: boolean
): any
//# sourceMappingURL=ListCredentialRepresentations200ResponseInner.d.ts.map
