'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfListIssuanceFlows401Response = instanceOfListIssuanceFlows401Response;
exports.ListIssuanceFlows401ResponseFromJSON = ListIssuanceFlows401ResponseFromJSON;
exports.ListIssuanceFlows401ResponseFromJSONTyped = ListIssuanceFlows401ResponseFromJSONTyped;
exports.ListIssuanceFlows401ResponseToJSON = ListIssuanceFlows401ResponseToJSON;
exports.ListIssuanceFlows401ResponseToJSONTyped = ListIssuanceFlows401ResponseToJSONTyped;
/**
 * Check if a given object implements the ListIssuanceFlows401Response interface.
 */
function instanceOfListIssuanceFlows401Response(value) {
    return true;
}
function ListIssuanceFlows401ResponseFromJSON(json) {
    return ListIssuanceFlows401ResponseFromJSONTyped(json, false);
}
function ListIssuanceFlows401ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'message': json['message'] == null ? undefined : json['message'],
    };
}
function ListIssuanceFlows401ResponseToJSON(json) {
    return ListIssuanceFlows401ResponseToJSONTyped(json, false);
}
function ListIssuanceFlows401ResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'message': value['message'],
    };
}
//# sourceMappingURL=ListIssuanceFlows401Response.js.map