'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPresentationFlowsResponse = instanceOfPresentationFlowsResponse;
exports.PresentationFlowsResponseFromJSON = PresentationFlowsResponseFromJSON;
exports.PresentationFlowsResponseFromJSONTyped = PresentationFlowsResponseFromJSONTyped;
exports.PresentationFlowsResponseToJSON = PresentationFlowsResponseToJSON;
exports.PresentationFlowsResponseToJSONTyped = PresentationFlowsResponseToJSONTyped;
const PresentationFlow_1 = require("./PresentationFlow");
/**
 * Check if a given object implements the PresentationFlowsResponse interface.
 */
function instanceOfPresentationFlowsResponse(value) {
    return true;
}
function PresentationFlowsResponseFromJSON(json) {
    return PresentationFlowsResponseFromJSONTyped(json, false);
}
function PresentationFlowsResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'presentationFlows': json['presentationFlows'] == null ? undefined : (json['presentationFlows'].map(PresentationFlow_1.PresentationFlowFromJSON)),
    };
}
function PresentationFlowsResponseToJSON(json) {
    return PresentationFlowsResponseToJSONTyped(json, false);
}
function PresentationFlowsResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'presentationFlows': value['presentationFlows'] == null ? undefined : (value['presentationFlows'].map(PresentationFlow_1.PresentationFlowToJSON)),
    };
}
//# sourceMappingURL=PresentationFlowsResponse.js.map