/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { PresentationFlow } from '../../src/models/PresentationFlow'

/**
 *
 * @export
 * @interface PresentationFlowResponse
 */
export interface PresentationFlowResponse {
  /**
   *
   * @type {PresentationFlow}
   * @memberof PresentationFlowResponse
   */
  presentationFlow?: PresentationFlow
}
/**
 * Check if a given object implements the PresentationFlowResponse interface.
 */
export declare function instanceOfPresentationFlowResponse(value: object): value is PresentationFlowResponse
export declare function PresentationFlowResponseFromJSON(json: any): PresentationFlowResponse
export declare function PresentationFlowResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PresentationFlowResponse
export declare function PresentationFlowResponseToJSON(json: any): PresentationFlowResponse
export declare function PresentationFlowResponseToJSONTyped(
  value?: PresentationFlowResponse | null,
  ignoreDiscriminator?: boolean
): any
//# sourceMappingURL=PresentationFlowResponse.d.ts.map
