'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShowcaseScenariosInnerFromJSON = ShowcaseScenariosInnerFromJSON;
exports.ShowcaseScenariosInnerFromJSONTyped = ShowcaseScenariosInnerFromJSONTyped;
exports.ShowcaseScenariosInnerToJSON = ShowcaseScenariosInnerToJSON;
exports.ShowcaseScenariosInnerToJSONTyped = ShowcaseScenariosInnerToJSONTyped;
const Id_1 = require("./Id");
const Scenario_1 = require("./Scenario");
function ShowcaseScenariosInnerFromJSON(json) {
    return ShowcaseScenariosInnerFromJSONTyped(json, false);
}
function ShowcaseScenariosInnerFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    if ((0, Id_1.instanceOfId)(json)) {
        return (0, Id_1.IdFromJSONTyped)(json, true);
    }
    if ((0, Scenario_1.instanceOfScenario)(json)) {
        return (0, Scenario_1.ScenarioFromJSONTyped)(json, true);
    }
    return {};
}
function ShowcaseScenariosInnerToJSON(json) {
    return ShowcaseScenariosInnerToJSONTyped(json, false);
}
function ShowcaseScenariosInnerToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    if ((0, Id_1.instanceOfId)(value)) {
        return (0, Id_1.IdToJSON)(value);
    }
    if ((0, Scenario_1.instanceOfScenario)(value)) {
        return (0, Scenario_1.ScenarioToJSON)(value);
    }
    return {};
}
//# sourceMappingURL=ShowcaseScenariosInner.js.map