/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ShowcaseStatus } from '../../src/models/ShowcaseStatus'

/**
 *
 * @export
 * @interface ShowcaseRequest
 */
export interface ShowcaseRequest {
  /**
   * Name of the showcase
   * @type {string}
   * @memberof ShowcaseRequest
   */
  name: string
  /**
   * Description of the showcase
   * @type {string}
   * @memberof ShowcaseRequest
   */
  description: string
  /**
   *
   * @type {ShowcaseStatus}
   * @memberof ShowcaseRequest
   */
  status: ShowcaseStatus
  /**
   * Whether the showcase is hidden from public view
   * @type {boolean}
   * @memberof ShowcaseRequest
   */
  hidden: boolean
  /**
   * List of scenarios in this showcase
   * @type {Array<string>}
   * @memberof ShowcaseRequest
   */
  scenarios: Array<string>
  /**
   * List of credential definitions used in this showcase
   * @type {Array<string>}
   * @memberof ShowcaseRequest
   */
  credentialDefinitions: Array<string>
  /**
   * List of personas involved in this showcase
   * @type {Array<string>}
   * @memberof ShowcaseRequest
   */
  personas: Array<string>
  /**
   *
   * @type {string}
   * @memberof ShowcaseRequest
   */
  bannerImage?: string
  /**
   *
   * @type {string}
   * @memberof ShowcaseRequest
   */
  completionMessage?: string
}
/**
 * Check if a given object implements the ShowcaseRequest interface.
 */
export declare function instanceOfShowcaseRequest(value: object): value is ShowcaseRequest
export declare function ShowcaseRequestFromJSON(json: any): ShowcaseRequest
export declare function ShowcaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowcaseRequest
export declare function ShowcaseRequestToJSON(json: any): ShowcaseRequest
export declare function ShowcaseRequestToJSONTyped(value?: ShowcaseRequest | null, ignoreDiscriminator?: boolean): any
//# sourceMappingURL=ShowcaseRequest.d.ts.map
