/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Types of supported credentials
 * @export
 */
export declare const ShowcaseStatus: {
  readonly Pending: 'PENDING'
  readonly Active: 'ACTIVE'
  readonly Archived: 'ARCHIVED'
}
export type ShowcaseStatus = (typeof ShowcaseStatus)[keyof typeof ShowcaseStatus]
export declare function instanceOfShowcaseStatus(value: any): boolean
export declare function ShowcaseStatusFromJSON(json: any): ShowcaseStatus
export declare function ShowcaseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowcaseStatus
export declare function ShowcaseStatusToJSON(value?: ShowcaseStatus | null): any
export declare function ShowcaseStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ShowcaseStatus
//# sourceMappingURL=ShowcaseStatus.d.ts.map
