'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfStepActionResponse = instanceOfStepActionResponse;
exports.StepActionResponseFromJSON = StepActionResponseFromJSON;
exports.StepActionResponseFromJSONTyped = StepActionResponseFromJSONTyped;
exports.StepActionResponseToJSON = StepActionResponseToJSON;
exports.StepActionResponseToJSONTyped = StepActionResponseToJSONTyped;
const StepAction_1 = require("./StepAction");
/**
 * Check if a given object implements the StepActionResponse interface.
 */
function instanceOfStepActionResponse(value) {
    return true;
}
function StepActionResponseFromJSON(json) {
    return StepActionResponseFromJSONTyped(json, false);
}
function StepActionResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'action': json['action'] == null ? undefined : (0, StepAction_1.StepActionFromJSON)(json['action']),
    };
}
function StepActionResponseToJSON(json) {
    return StepActionResponseToJSONTyped(json, false);
}
function StepActionResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'action': (0, StepAction_1.StepActionToJSON)(value['action']),
    };
}
//# sourceMappingURL=StepActionResponse.js.map