/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AriesOOBActionRequest } from '../../src/models/AriesOOBActionRequest'

/**
 * @type StepRequestActionsInner
 *
 * @export
 */
export type StepRequestActionsInner = AriesOOBActionRequest
export declare function StepRequestActionsInnerFromJSON(json: any): StepRequestActionsInner
export declare function StepRequestActionsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): StepRequestActionsInner
export declare function StepRequestActionsInnerToJSON(json: any): any
export declare function StepRequestActionsInnerToJSONTyped(
  value?: StepRequestActionsInner | null,
  ignoreDiscriminator?: boolean
): any
//# sourceMappingURL=StepRequestActionsInner.d.ts.map
