/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Anonymous Credentials specific revocation information
 * @export
 * @interface AnonCredRevocation
 */
export interface AnonCredRevocation {
    /**
     * Id of the revocation information
     * @type {string}
     * @memberof AnonCredRevocation
     */
    id: string;
    /**
     * Title of the revocation information
     * @type {string}
     * @memberof AnonCredRevocation
     */
    title: string;
    /**
     * Detailed description of the revocation process or requirements
     * @type {string}
     * @memberof AnonCredRevocation
     */
    description: string;
    /**
     * Date and time the Revocation info was created
     * @type {Date}
     * @memberof AnonCredRevocation
     */
    createdAt: Date;
    /**
     * Date and time the Revocation info was last updated
     * @type {Date}
     * @memberof AnonCredRevocation
     */
    updatedAt: Date;
    /**
     * Identifier of the revocation registry for AnonCreds
     * @type {string}
     * @memberof AnonCredRevocation
     */
    registryId: string;
}
/**
 * Check if a given object implements the AnonCredRevocation interface.
 */
export declare function instanceOfAnonCredRevocation(value: object): value is AnonCredRevocation;
export declare function AnonCredRevocationFromJSON(json: any): AnonCredRevocation;
export declare function AnonCredRevocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnonCredRevocation;
export declare function AnonCredRevocationToJSON(json: any): AnonCredRevocation;
export declare function AnonCredRevocationToJSONTyped(value?: AnonCredRevocation | null, ignoreDiscriminator?: boolean): any;
//# sourceMappingURL=AnonCredRevocation.d.ts.map