"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAnonCredRevocation = instanceOfAnonCredRevocation;
exports.AnonCredRevocationFromJSON = AnonCredRevocationFromJSON;
exports.AnonCredRevocationFromJSONTyped = AnonCredRevocationFromJSONTyped;
exports.AnonCredRevocationToJSON = AnonCredRevocationToJSON;
exports.AnonCredRevocationToJSONTyped = AnonCredRevocationToJSONTyped;
/**
 * Check if a given object implements the AnonCredRevocation interface.
 */
function instanceOfAnonCredRevocation(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('title' in value) || value['title'] === undefined)
        return false;
    if (!('description' in value) || value['description'] === undefined)
        return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined)
        return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined)
        return false;
    if (!('registryId' in value) || value['registryId'] === undefined)
        return false;
    return true;
}
function AnonCredRevocationFromJSON(json) {
    return AnonCredRevocationFromJSONTyped(json, false);
}
function AnonCredRevocationFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'registryId': json['registryId'],
    };
}
function AnonCredRevocationToJSON(json) {
    return AnonCredRevocationToJSONTyped(json, false);
}
function AnonCredRevocationToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'registryId': value['registryId'],
    };
}
//# sourceMappingURL=AnonCredRevocation.js.map