"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAriesOOBAction = instanceOfAriesOOBAction;
exports.AriesOOBActionFromJSON = AriesOOBActionFromJSON;
exports.AriesOOBActionFromJSONTyped = AriesOOBActionFromJSONTyped;
exports.AriesOOBActionToJSON = AriesOOBActionToJSON;
exports.AriesOOBActionToJSONTyped = AriesOOBActionToJSONTyped;
const AriesProofRequest_1 = require("./AriesProofRequest");
const StepAction_1 = require("./StepAction");
/**
 * Check if a given object implements the AriesOOBAction interface.
 */
function instanceOfAriesOOBAction(value) {
    if (!('proofRequest' in value) || value['proofRequest'] === undefined)
        return false;
    return true;
}
function AriesOOBActionFromJSON(json) {
    return AriesOOBActionFromJSONTyped(json, false);
}
function AriesOOBActionFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return Object.assign(Object.assign({}, (0, StepAction_1.StepActionFromJSONTyped)(json, true)), { 'proofRequest': (0, AriesProofRequest_1.AriesProofRequestFromJSON)(json['proofRequest']) });
}
function AriesOOBActionToJSON(json) {
    return AriesOOBActionToJSONTyped(json, false);
}
function AriesOOBActionToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return Object.assign(Object.assign({}, (0, StepAction_1.StepActionToJSONTyped)(value, true)), { 'proofRequest': (0, AriesProofRequest_1.AriesProofRequestToJSON)(value['proofRequest']) });
}
//# sourceMappingURL=AriesOOBAction.js.map