'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAriesRequestCredentialPredicates = instanceOfAriesRequestCredentialPredicates;
exports.AriesRequestCredentialPredicatesFromJSON = AriesRequestCredentialPredicatesFromJSON;
exports.AriesRequestCredentialPredicatesFromJSONTyped = AriesRequestCredentialPredicatesFromJSONTyped;
exports.AriesRequestCredentialPredicatesToJSON = AriesRequestCredentialPredicatesToJSON;
exports.AriesRequestCredentialPredicatesToJSONTyped = AriesRequestCredentialPredicatesToJSONTyped;
/**
 * Check if a given object implements the AriesRequestCredentialPredicates interface.
 */
function instanceOfAriesRequestCredentialPredicates(value) {
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('type' in value) || value['type'] === undefined)
        return false;
    if (!('value' in value) || value['value'] === undefined)
        return false;
    if (!('restrictions' in value) || value['restrictions'] === undefined)
        return false;
    return true;
}
function AriesRequestCredentialPredicatesFromJSON(json) {
    return AriesRequestCredentialPredicatesFromJSONTyped(json, false);
}
function AriesRequestCredentialPredicatesFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'],
        'type': json['type'],
        'value': json['value'],
        'restrictions': json['restrictions'],
    };
}
function AriesRequestCredentialPredicatesToJSON(json) {
    return AriesRequestCredentialPredicatesToJSONTyped(json, false);
}
function AriesRequestCredentialPredicatesToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'type': value['type'],
        'value': value['value'],
        'restrictions': value['restrictions'],
    };
}
//# sourceMappingURL=AriesRequestCredentialPredicates.js.map