"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAssetsResponse = instanceOfAssetsResponse;
exports.AssetsResponseFromJSON = AssetsResponseFromJSON;
exports.AssetsResponseFromJSONTyped = AssetsResponseFromJSONTyped;
exports.AssetsResponseToJSON = AssetsResponseToJSON;
exports.AssetsResponseToJSONTyped = AssetsResponseToJSONTyped;
const Asset_1 = require("./Asset");
/**
 * Check if a given object implements the AssetsResponse interface.
 */
function instanceOfAssetsResponse(value) {
    if (!('assets' in value) || value['assets'] === undefined)
        return false;
    return true;
}
function AssetsResponseFromJSON(json) {
    return AssetsResponseFromJSONTyped(json, false);
}
function AssetsResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'assets': (json['assets'].map(Asset_1.AssetFromJSON)),
    };
}
function AssetsResponseToJSON(json) {
    return AssetsResponseToJSONTyped(json, false);
}
function AssetsResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'assets': (value['assets'].map(Asset_1.AssetToJSON)),
    };
}
//# sourceMappingURL=AssetsResponse.js.map