"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAsset = instanceOfAsset;
exports.AssetFromJSON = AssetFromJSON;
exports.AssetFromJSONTyped = AssetFromJSONTyped;
exports.AssetToJSON = AssetToJSON;
exports.AssetToJSONTyped = AssetToJSONTyped;
/**
 * Check if a given object implements the Asset interface.
 */
function instanceOfAsset(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    return true;
}
function AssetFromJSON(json) {
    return AssetFromJSONTyped(json, false);
}
function AssetFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'mediaType': json['mediaType'] == null ? undefined : json['mediaType'],
        'content': json['content'] == null ? undefined : json['content'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}
function AssetToJSON(json) {
    return AssetToJSONTyped(json, false);
}
function AssetToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'mediaType': value['mediaType'],
        'content': value['content'],
        'fileName': value['fileName'],
        'description': value['description'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}
//# sourceMappingURL=Asset.js.map