/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Asset
 */
export interface Asset {
    /**
     * Unique identifier for the asset in the database
     * @type {string}
     * @memberof Asset
     */
    id: string;
    /**
     * Type of asset (e.g., image, document, icon)
     * @type {string}
     * @memberof Asset
     */
    mediaType?: string;
    /**
     * Binary data of the asset
     * @type {string}
     * @memberof Asset
     */
    content?: string;
    /**
     * Name of the asset file
     * @type {string}
     * @memberof Asset
     */
    fileName?: string;
    /**
     * Description of the asset
     * @type {string}
     * @memberof Asset
     */
    description?: string;
    /**
     * Date and time the asset was created
     * @type {Date}
     * @memberof Asset
     */
    createdAt?: Date;
    /**
     * Date and time the asset was last updated
     * @type {Date}
     * @memberof Asset
     */
    updatedAt?: Date;
}
/**
 * Check if a given object implements the Asset interface.
 */
export declare function instanceOfAsset(value: object): value is Asset;
export declare function AssetFromJSON(json: any): Asset;
export declare function AssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Asset;
export declare function AssetToJSON(json: any): Asset;
export declare function AssetToJSONTyped(value?: Asset | null, ignoreDiscriminator?: boolean): any;
//# sourceMappingURL=Asset.d.ts.map