"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfCredentialDefinitionResponse = instanceOfCredentialDefinitionResponse;
exports.CredentialDefinitionResponseFromJSON = CredentialDefinitionResponseFromJSON;
exports.CredentialDefinitionResponseFromJSONTyped = CredentialDefinitionResponseFromJSONTyped;
exports.CredentialDefinitionResponseToJSON = CredentialDefinitionResponseToJSON;
exports.CredentialDefinitionResponseToJSONTyped = CredentialDefinitionResponseToJSONTyped;
const CredentialDefinition_1 = require("./CredentialDefinition");
/**
 * Check if a given object implements the CredentialDefinitionResponse interface.
 */
function instanceOfCredentialDefinitionResponse(value) {
    return true;
}
function CredentialDefinitionResponseFromJSON(json) {
    return CredentialDefinitionResponseFromJSONTyped(json, false);
}
function CredentialDefinitionResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'credentialDefinition': json['credentialDefinition'] == null ? undefined : (0, CredentialDefinition_1.CredentialDefinitionFromJSON)(json['credentialDefinition']),
    };
}
function CredentialDefinitionResponseToJSON(json) {
    return CredentialDefinitionResponseToJSONTyped(json, false);
}
function CredentialDefinitionResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'credentialDefinition': (0, CredentialDefinition_1.CredentialDefinitionToJSON)(value['credentialDefinition']),
    };
}
//# sourceMappingURL=CredentialDefinitionResponse.js.map