/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CredentialDefinition } from './CredentialDefinition';
/**
 *
 * @export
 * @interface CredentialDefinitionResponse
 */
export interface CredentialDefinitionResponse {
    /**
     *
     * @type {CredentialDefinition}
     * @memberof CredentialDefinitionResponse
     */
    credentialDefinition?: CredentialDefinition;
}
/**
 * Check if a given object implements the CredentialDefinitionResponse interface.
 */
export declare function instanceOfCredentialDefinitionResponse(value: object): value is CredentialDefinitionResponse;
export declare function CredentialDefinitionResponseFromJSON(json: any): CredentialDefinitionResponse;
export declare function CredentialDefinitionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialDefinitionResponse;
export declare function CredentialDefinitionResponseToJSON(json: any): CredentialDefinitionResponse;
export declare function CredentialDefinitionResponseToJSONTyped(value?: CredentialDefinitionResponse | null, ignoreDiscriminator?: boolean): any;
//# sourceMappingURL=CredentialDefinitionResponse.d.ts.map