'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CredentialType = void 0;
exports.instanceOfCredentialType = instanceOfCredentialType;
exports.CredentialTypeFromJSON = CredentialTypeFromJSON;
exports.CredentialTypeFromJSONTyped = CredentialTypeFromJSONTyped;
exports.CredentialTypeToJSON = CredentialTypeToJSON;
exports.CredentialTypeToJSONTyped = CredentialTypeToJSONTyped;
/**
 * Types of supported credentials
 * @export
 */
exports.CredentialType = {
    Anoncred: 'ANONCRED'
};
function instanceOfCredentialType(value) {
    for (const key in exports.CredentialType) {
        if (Object.prototype.hasOwnProperty.call(exports.CredentialType, key)) {
            if (exports.CredentialType[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function CredentialTypeFromJSON(json) {
    return CredentialTypeFromJSONTyped(json, false);
}
function CredentialTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function CredentialTypeToJSON(value) {
    return value;
}
function CredentialTypeToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
//# sourceMappingURL=CredentialType.js.map