"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CredentialDefinitionRequestRepresentationsInnerFromJSON = CredentialDefinitionRequestRepresentationsInnerFromJSON;
exports.CredentialDefinitionRequestRepresentationsInnerFromJSONTyped = CredentialDefinitionRequestRepresentationsInnerFromJSONTyped;
exports.CredentialDefinitionRequestRepresentationsInnerToJSON = CredentialDefinitionRequestRepresentationsInnerToJSON;
exports.CredentialDefinitionRequestRepresentationsInnerToJSONTyped = CredentialDefinitionRequestRepresentationsInnerToJSONTyped;
const CredentialRepresentation_1 = require("./CredentialRepresentation");
const OCARepresentation_1 = require("./OCARepresentation");
function CredentialDefinitionRequestRepresentationsInnerFromJSON(json) {
    return CredentialDefinitionRequestRepresentationsInnerFromJSONTyped(json, false);
}
function CredentialDefinitionRequestRepresentationsInnerFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    if ((0, CredentialRepresentation_1.instanceOfCredentialRepresentation)(json)) {
        return (0, CredentialRepresentation_1.CredentialRepresentationFromJSONTyped)(json, true);
    }
    if ((0, OCARepresentation_1.instanceOfOCARepresentation)(json)) {
        return (0, OCARepresentation_1.OCARepresentationFromJSONTyped)(json, true);
    }
    return {};
}
function CredentialDefinitionRequestRepresentationsInnerToJSON(json) {
    return CredentialDefinitionRequestRepresentationsInnerToJSONTyped(json, false);
}
function CredentialDefinitionRequestRepresentationsInnerToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    if ((0, CredentialRepresentation_1.instanceOfCredentialRepresentation)(value)) {
        return (0, CredentialRepresentation_1.CredentialRepresentationToJSON)(value);
    }
    if ((0, OCARepresentation_1.instanceOfOCARepresentation)(value)) {
        return (0, OCARepresentation_1.OCARepresentationToJSON)(value);
    }
    return {};
}
//# sourceMappingURL=CredentialDefinitionRequestRepresentationsInner.js.map