/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CredentialDefinition } from './CredentialDefinition';
/**
 *
 * @export
 * @interface CredentialDefinitionsResponse
 */
export interface CredentialDefinitionsResponse {
    /**
     * List of credential definitions
     * @type {Array<CredentialDefinition>}
     * @memberof CredentialDefinitionsResponse
     */
    credentialDefinitions?: Array<CredentialDefinition>;
}
/**
 * Check if a given object implements the CredentialDefinitionsResponse interface.
 */
export declare function instanceOfCredentialDefinitionsResponse(value: object): value is CredentialDefinitionsResponse;
export declare function CredentialDefinitionsResponseFromJSON(json: any): CredentialDefinitionsResponse;
export declare function CredentialDefinitionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialDefinitionsResponse;
export declare function CredentialDefinitionsResponseToJSON(json: any): CredentialDefinitionsResponse;
export declare function CredentialDefinitionsResponseToJSONTyped(value?: CredentialDefinitionsResponse | null, ignoreDiscriminator?: boolean): any;
//# sourceMappingURL=CredentialDefinitionsResponse.d.ts.map