"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfCredentialRepresentation = instanceOfCredentialRepresentation;
exports.CredentialRepresentationFromJSON = CredentialRepresentationFromJSON;
exports.CredentialRepresentationFromJSONTyped = CredentialRepresentationFromJSONTyped;
exports.CredentialRepresentationToJSON = CredentialRepresentationToJSON;
exports.CredentialRepresentationToJSONTyped = CredentialRepresentationToJSONTyped;
/**
 * Check if a given object implements the CredentialRepresentation interface.
 */
function instanceOfCredentialRepresentation(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined)
        return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined)
        return false;
    return true;
}
function CredentialRepresentationFromJSON(json) {
    return CredentialRepresentationFromJSONTyped(json, false);
}
function CredentialRepresentationFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}
function CredentialRepresentationToJSON(json) {
    return CredentialRepresentationToJSONTyped(json, false);
}
function CredentialRepresentationToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}
//# sourceMappingURL=CredentialRepresentation.js.map