/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CredentialAttributeType } from './CredentialAttributeType';
/**
 *
 * @export
 * @interface CredentialAttributeRequest
 */
export interface CredentialAttributeRequest {
    /**
     * Name of the attribute
     * @type {string}
     * @memberof CredentialAttributeRequest
     */
    name: string;
    /**
     * Default or example value of the attribute
     * @type {string}
     * @memberof CredentialAttributeRequest
     */
    value: string;
    /**
     *
     * @type {CredentialAttributeType}
     * @memberof CredentialAttributeRequest
     */
    type: CredentialAttributeType;
}
/**
 * Check if a given object implements the CredentialAttributeRequest interface.
 */
export declare function instanceOfCredentialAttributeRequest(value: object): value is CredentialAttributeRequest;
export declare function CredentialAttributeRequestFromJSON(json: any): CredentialAttributeRequest;
export declare function CredentialAttributeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialAttributeRequest;
export declare function CredentialAttributeRequestToJSON(json: any): CredentialAttributeRequest;
export declare function CredentialAttributeRequestToJSONTyped(value?: CredentialAttributeRequest | null, ignoreDiscriminator?: boolean): any;
//# sourceMappingURL=CredentialAttributeRequest.d.ts.map