/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface DeleteShowcase204Response
 */
export interface DeleteShowcase204Response {
    /**
     * A message indicating the showcase was deleted
     * @type {string}
     * @memberof DeleteShowcase204Response
     */
    message?: string;
}
/**
 * Check if a given object implements the DeleteShowcase204Response interface.
 */
export declare function instanceOfDeleteShowcase204Response(value: object): value is DeleteShowcase204Response;
export declare function DeleteShowcase204ResponseFromJSON(json: any): DeleteShowcase204Response;
export declare function DeleteShowcase204ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteShowcase204Response;
export declare function DeleteShowcase204ResponseToJSON(json: any): DeleteShowcase204Response;
export declare function DeleteShowcase204ResponseToJSONTyped(value?: DeleteShowcase204Response | null, ignoreDiscriminator?: boolean): any;
//# sourceMappingURL=DeleteShowcase204Response.d.ts.map