/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface GetIssuanceFlow404Response
 */
export interface GetIssuanceFlow404Response {
    /**
     *
     * @type {string}
     * @memberof GetIssuanceFlow404Response
     */
    message?: string;
}
/**
 * Check if a given object implements the GetIssuanceFlow404Response interface.
 */
export declare function instanceOfGetIssuanceFlow404Response(value: object): value is GetIssuanceFlow404Response;
export declare function GetIssuanceFlow404ResponseFromJSON(json: any): GetIssuanceFlow404Response;
export declare function GetIssuanceFlow404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetIssuanceFlow404Response;
export declare function GetIssuanceFlow404ResponseToJSON(json: any): GetIssuanceFlow404Response;
export declare function GetIssuanceFlow404ResponseToJSONTyped(value?: GetIssuanceFlow404Response | null, ignoreDiscriminator?: boolean): any;
//# sourceMappingURL=GetIssuanceFlow404Response.d.ts.map