/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface GetIssuanceScenario404Response
 */
export interface GetIssuanceScenario404Response {
  /**
   *
   * @type {string}
   * @memberof GetIssuanceScenario404Response
   */
  message?: string
}
/**
 * Check if a given object implements the GetIssuanceScenario404Response interface.
 */
export declare function instanceOfGetIssuanceScenario404Response(value: object): value is GetIssuanceScenario404Response
export declare function GetIssuanceScenario404ResponseFromJSON(json: any): GetIssuanceScenario404Response
export declare function GetIssuanceScenario404ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetIssuanceScenario404Response
export declare function GetIssuanceScenario404ResponseToJSON(json: any): GetIssuanceScenario404Response
export declare function GetIssuanceScenario404ResponseToJSONTyped(
  value?: GetIssuanceScenario404Response | null,
  ignoreDiscriminator?: boolean
): any
//# sourceMappingURL=GetIssuanceScenario404Response.d.ts.map
