"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfGetIssuanceFlow404Response = instanceOfGetIssuanceFlow404Response;
exports.GetIssuanceFlow404ResponseFromJSON = GetIssuanceFlow404ResponseFromJSON;
exports.GetIssuanceFlow404ResponseFromJSONTyped = GetIssuanceFlow404ResponseFromJSONTyped;
exports.GetIssuanceFlow404ResponseToJSON = GetIssuanceFlow404ResponseToJSON;
exports.GetIssuanceFlow404ResponseToJSONTyped = GetIssuanceFlow404ResponseToJSONTyped;
/**
 * Check if a given object implements the GetIssuanceFlow404Response interface.
 */
function instanceOfGetIssuanceFlow404Response(value) {
    return true;
}
function GetIssuanceFlow404ResponseFromJSON(json) {
    return GetIssuanceFlow404ResponseFromJSONTyped(json, false);
}
function GetIssuanceFlow404ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'message': json['message'] == null ? undefined : json['message'],
    };
}
function GetIssuanceFlow404ResponseToJSON(json) {
    return GetIssuanceFlow404ResponseToJSONTyped(json, false);
}
function GetIssuanceFlow404ResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'message': value['message'],
    };
}
//# sourceMappingURL=GetIssuanceFlow404Response.js.map