/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Types of supported identifiers
 * @export
 */
export declare const IdentifierType: {
  readonly Did: 'DID'
}
export type IdentifierType = (typeof IdentifierType)[keyof typeof IdentifierType]
export declare function instanceOfIdentifierType(value: any): boolean
export declare function IdentifierTypeFromJSON(json: any): IdentifierType
export declare function IdentifierTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentifierType
export declare function IdentifierTypeToJSON(value?: IdentifierType | null): any
export declare function IdentifierTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): IdentifierType
//# sourceMappingURL=IdentifierType.d.ts.map
