/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { IssuanceScenario } from './IssuanceScenario';
/**
 *
 * @export
 * @interface IssuanceScenariosResponse
 */
export interface IssuanceScenariosResponse {
    /**
     *
     * @type {Array<IssuanceScenario>}
     * @memberof IssuanceScenariosResponse
     */
    issuanceScenarios?: Array<IssuanceScenario>;
}
/**
 * Check if a given object implements the IssuanceScenariosResponse interface.
 */
export declare function instanceOfIssuanceScenariosResponse(value: object): value is IssuanceScenariosResponse;
export declare function IssuanceScenariosResponseFromJSON(json: any): IssuanceScenariosResponse;
export declare function IssuanceScenariosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuanceScenariosResponse;
export declare function IssuanceScenariosResponseToJSON(json: any): IssuanceScenariosResponse;
export declare function IssuanceScenariosResponseToJSONTyped(value?: IssuanceScenariosResponse | null, ignoreDiscriminator?: boolean): any;
//# sourceMappingURL=IssuanceScenariosResponse.d.ts.map