/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Asset } from './Asset'
import type { CredentialDefinition } from './CredentialDefinition'
import type { CredentialSchema } from './CredentialSchema'
import type { IssuerType } from './IssuerType'

/**
 *
 * @export
 * @interface Issuer
 */
export interface Issuer {
  /**
   * Unique identifier for the issuer
   * @type {string}
   * @memberof Issuer
   */
  id: string
  /**
   * Name of the issuer
   * @type {string}
   * @memberof Issuer
   */
  name: string
  /**
   * Detailed description of the issuer
   * @type {string}
   * @memberof Issuer
   */
  description: string
  /**
   *
   * @type {IssuerType}
   * @memberof Issuer
   */
  type: IssuerType
  /**
   * Organization the issuer belongs to
   * @type {string}
   * @memberof Issuer
   */
  organization?: string
  /**
   * The asset id
   * @type {string}
   * @memberof Issuer
   */
  logoId?: string
  /**
   *
   * @type {Asset}
   * @memberof Issuer
   */
  logo?: Asset
  /**
   *
   * @type {Array<CredentialDefinition>}
   * @memberof Issuer
   */
  credentialDefinitions: Array<CredentialDefinition>
  /**
   *
   * @type {Array<CredentialSchema>}
   * @memberof Issuer
   */
  credentialSchemas: Array<CredentialSchema>
  /**
   * Date and time the issuer was created
   * @type {Date}
   * @memberof Issuer
   */
  createdAt: Date
  /**
   * Date and time the issuer was last updated
   * @type {Date}
   * @memberof Issuer
   */
  updatedAt: Date
}
/**
 * Check if a given object implements the Issuer interface.
 */
export declare function instanceOfIssuer(value: object): value is Issuer
export declare function IssuerFromJSON(json: any): Issuer
export declare function IssuerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Issuer
export declare function IssuerToJSON(json: any): Issuer
export declare function IssuerToJSONTyped(value?: Issuer | null, ignoreDiscriminator?: boolean): any
//# sourceMappingURL=Issuer.d.ts.map
