/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { StepRequest } from './StepRequest'

/**
 * Scenario specialization for credential issuance
 * @export
 * @interface IssuanceScenarioRequest
 */
export interface IssuanceScenarioRequest {
  /**
   * Name of the scenario
   * @type {string}
   * @memberof IssuanceScenarioRequest
   */
  name: string
  /**
   * Detailed description of the scenario
   * @type {string}
   * @memberof IssuanceScenarioRequest
   */
  description: string
  /**
   * Ordered list of steps in the scenario
   * @type {Array<StepRequest>}
   * @memberof IssuanceScenarioRequest
   */
  steps: Array<StepRequest>
  /**
   * References to personas used in this scenario
   * @type {Array<string>}
   * @memberof IssuanceScenarioRequest
   */
  personas: Array<string>
  /**
   * Whether the workflow is hidden from the user
   * @type {boolean}
   * @memberof IssuanceScenarioRequest
   */
  hidden?: boolean
  /**
   *
   * @type {string}
   * @memberof IssuanceScenarioRequest
   */
  issuer: string
}
/**
 * Check if a given object implements the IssuanceScenarioRequest interface.
 */
export declare function instanceOfIssuanceScenarioRequest(value: object): value is IssuanceScenarioRequest
export declare function IssuanceScenarioRequestFromJSON(json: any): IssuanceScenarioRequest
export declare function IssuanceScenarioRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IssuanceScenarioRequest
export declare function IssuanceScenarioRequestToJSON(json: any): IssuanceScenarioRequest
export declare function IssuanceScenarioRequestToJSONTyped(
  value?: IssuanceScenarioRequest | null,
  ignoreDiscriminator?: boolean
): any
//# sourceMappingURL=IssuanceScenarioRequest.d.ts.map
