'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfIssuerResponse = instanceOfIssuerResponse;
exports.IssuerResponseFromJSON = IssuerResponseFromJSON;
exports.IssuerResponseFromJSONTyped = IssuerResponseFromJSONTyped;
exports.IssuerResponseToJSON = IssuerResponseToJSON;
exports.IssuerResponseToJSONTyped = IssuerResponseToJSONTyped;
const Issuer_1 = require("./Issuer");
/**
 * Check if a given object implements the IssuerResponse interface.
 */
function instanceOfIssuerResponse(value) {
    return true;
}
function IssuerResponseFromJSON(json) {
    return IssuerResponseFromJSONTyped(json, false);
}
function IssuerResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'issuer': json['issuer'] == null ? undefined : (0, Issuer_1.IssuerFromJSON)(json['issuer']),
    };
}
function IssuerResponseToJSON(json) {
    return IssuerResponseToJSONTyped(json, false);
}
function IssuerResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'issuer': (0, Issuer_1.IssuerToJSON)(value['issuer']),
    };
}
//# sourceMappingURL=IssuerResponse.js.map