/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { IssuanceScenario } from './IssuanceScenario';
/**
 *
 * @export
 * @interface IssuanceScenarioResponse
 */
export interface IssuanceScenarioResponse {
    /**
     *
     * @type {IssuanceScenario}
     * @memberof IssuanceScenarioResponse
     */
    issuanceScenario?: IssuanceScenario;
}
/**
 * Check if a given object implements the IssuanceScenarioResponse interface.
 */
export declare function instanceOfIssuanceScenarioResponse(value: object): value is IssuanceScenarioResponse;
export declare function IssuanceScenarioResponseFromJSON(json: any): IssuanceScenarioResponse;
export declare function IssuanceScenarioResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuanceScenarioResponse;
export declare function IssuanceScenarioResponseToJSON(json: any): IssuanceScenarioResponse;
export declare function IssuanceScenarioResponseToJSONTyped(value?: IssuanceScenarioResponse | null, ignoreDiscriminator?: boolean): any;
//# sourceMappingURL=IssuanceScenarioResponse.d.ts.map