"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IssuerType = void 0;
exports.instanceOfIssuerType = instanceOfIssuerType;
exports.IssuerTypeFromJSON = IssuerTypeFromJSON;
exports.IssuerTypeFromJSONTyped = IssuerTypeFromJSONTyped;
exports.IssuerTypeToJSON = IssuerTypeToJSON;
exports.IssuerTypeToJSONTyped = IssuerTypeToJSONTyped;
/**
 * Types of supported issuers
 * @export
 */
exports.IssuerType = {
    Aries: 'ARIES'
};
function instanceOfIssuerType(value) {
    for (const key in exports.IssuerType) {
        if (Object.prototype.hasOwnProperty.call(exports.IssuerType, key)) {
            if (exports.IssuerType[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function IssuerTypeFromJSON(json) {
    return IssuerTypeFromJSONTyped(json, false);
}
function IssuerTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function IssuerTypeToJSON(value) {
    return value;
}
function IssuerTypeToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
//# sourceMappingURL=IssuerType.js.map