"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfIssuanceFlowResponse = instanceOfIssuanceFlowResponse;
exports.IssuanceFlowResponseFromJSON = IssuanceFlowResponseFromJSON;
exports.IssuanceFlowResponseFromJSONTyped = IssuanceFlowResponseFromJSONTyped;
exports.IssuanceFlowResponseToJSON = IssuanceFlowResponseToJSON;
exports.IssuanceFlowResponseToJSONTyped = IssuanceFlowResponseToJSONTyped;
const IssuanceFlow_1 = require("./IssuanceFlow");
/**
 * Check if a given object implements the IssuanceFlowResponse interface.
 */
function instanceOfIssuanceFlowResponse(value) {
    return true;
}
function IssuanceFlowResponseFromJSON(json) {
    return IssuanceFlowResponseFromJSONTyped(json, false);
}
function IssuanceFlowResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'issuanceFlow': json['issuanceFlow'] == null ? undefined : (0, IssuanceFlow_1.IssuanceFlowFromJSON)(json['issuanceFlow']),
    };
}
function IssuanceFlowResponseToJSON(json) {
    return IssuanceFlowResponseToJSONTyped(json, false);
}
function IssuanceFlowResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'issuanceFlow': (0, IssuanceFlow_1.IssuanceFlowToJSON)(value['issuanceFlow']),
    };
}
//# sourceMappingURL=IssuanceFlowResponse.js.map