/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Types of supported issuers
 * @export
 */
export declare const IssuerType: {
  readonly Aries: 'ARIES'
}
export type IssuerType = (typeof IssuerType)[keyof typeof IssuerType]
export declare function instanceOfIssuerType(value: any): boolean
export declare function IssuerTypeFromJSON(json: any): IssuerType
export declare function IssuerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuerType
export declare function IssuerTypeToJSON(value?: IssuerType | null): any
export declare function IssuerTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): IssuerType
//# sourceMappingURL=IssuerType.d.ts.map
