"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfIssuanceScenarioResponse = instanceOfIssuanceScenarioResponse;
exports.IssuanceScenarioResponseFromJSON = IssuanceScenarioResponseFromJSON;
exports.IssuanceScenarioResponseFromJSONTyped = IssuanceScenarioResponseFromJSONTyped;
exports.IssuanceScenarioResponseToJSON = IssuanceScenarioResponseToJSON;
exports.IssuanceScenarioResponseToJSONTyped = IssuanceScenarioResponseToJSONTyped;
const IssuanceScenario_1 = require("./IssuanceScenario");
/**
 * Check if a given object implements the IssuanceScenarioResponse interface.
 */
function instanceOfIssuanceScenarioResponse(value) {
    return true;
}
function IssuanceScenarioResponseFromJSON(json) {
    return IssuanceScenarioResponseFromJSONTyped(json, false);
}
function IssuanceScenarioResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'issuanceScenario': json['issuanceScenario'] == null ? undefined : (0, IssuanceScenario_1.IssuanceScenarioFromJSON)(json['issuanceScenario']),
    };
}
function IssuanceScenarioResponseToJSON(json) {
    return IssuanceScenarioResponseToJSONTyped(json, false);
}
function IssuanceScenarioResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'issuanceScenario': (0, IssuanceScenario_1.IssuanceScenarioToJSON)(value['issuanceScenario']),
    };
}
//# sourceMappingURL=IssuanceScenarioResponse.js.map