"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfListIssuanceScenarios401Response = instanceOfListIssuanceScenarios401Response;
exports.ListIssuanceScenarios401ResponseFromJSON = ListIssuanceScenarios401ResponseFromJSON;
exports.ListIssuanceScenarios401ResponseFromJSONTyped = ListIssuanceScenarios401ResponseFromJSONTyped;
exports.ListIssuanceScenarios401ResponseToJSON = ListIssuanceScenarios401ResponseToJSON;
exports.ListIssuanceScenarios401ResponseToJSONTyped = ListIssuanceScenarios401ResponseToJSONTyped;
/**
 * Check if a given object implements the ListIssuanceScenarios401Response interface.
 */
function instanceOfListIssuanceScenarios401Response(value) {
    return true;
}
function ListIssuanceScenarios401ResponseFromJSON(json) {
    return ListIssuanceScenarios401ResponseFromJSONTyped(json, false);
}
function ListIssuanceScenarios401ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'message': json['message'] == null ? undefined : json['message'],
    };
}
function ListIssuanceScenarios401ResponseToJSON(json) {
    return ListIssuanceScenarios401ResponseToJSONTyped(json, false);
}
function ListIssuanceScenarios401ResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'message': value['message'],
    };
}
//# sourceMappingURL=ListIssuanceScenarios401Response.js.map