/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ListIssuanceScenarios400Response
 */
export interface ListIssuanceScenarios400Response {
    /**
     *
     * @type {string}
     * @memberof ListIssuanceScenarios400Response
     */
    message?: string;
}
/**
 * Check if a given object implements the ListIssuanceScenarios400Response interface.
 */
export declare function instanceOfListIssuanceScenarios400Response(value: object): value is ListIssuanceScenarios400Response;
export declare function ListIssuanceScenarios400ResponseFromJSON(json: any): ListIssuanceScenarios400Response;
export declare function ListIssuanceScenarios400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListIssuanceScenarios400Response;
export declare function ListIssuanceScenarios400ResponseToJSON(json: any): ListIssuanceScenarios400Response;
export declare function ListIssuanceScenarios400ResponseToJSONTyped(value?: ListIssuanceScenarios400Response | null, ignoreDiscriminator?: boolean): any;
//# sourceMappingURL=ListIssuanceScenarios400Response.d.ts.map