/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ListIssuanceFlows401Response
 */
export interface ListIssuanceFlows401Response {
    /**
     *
     * @type {string}
     * @memberof ListIssuanceFlows401Response
     */
    message?: string;
}
/**
 * Check if a given object implements the ListIssuanceFlows401Response interface.
 */
export declare function instanceOfListIssuanceFlows401Response(value: object): value is ListIssuanceFlows401Response;
export declare function ListIssuanceFlows401ResponseFromJSON(json: any): ListIssuanceFlows401Response;
export declare function ListIssuanceFlows401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListIssuanceFlows401Response;
export declare function ListIssuanceFlows401ResponseToJSON(json: any): ListIssuanceFlows401Response;
export declare function ListIssuanceFlows401ResponseToJSONTyped(value?: ListIssuanceFlows401Response | null, ignoreDiscriminator?: boolean): any;
//# sourceMappingURL=ListIssuanceFlows401Response.d.ts.map