'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfListIssuanceScenarios500Response = instanceOfListIssuanceScenarios500Response;
exports.ListIssuanceScenarios500ResponseFromJSON = ListIssuanceScenarios500ResponseFromJSON;
exports.ListIssuanceScenarios500ResponseFromJSONTyped = ListIssuanceScenarios500ResponseFromJSONTyped;
exports.ListIssuanceScenarios500ResponseToJSON = ListIssuanceScenarios500ResponseToJSON;
exports.ListIssuanceScenarios500ResponseToJSONTyped = ListIssuanceScenarios500ResponseToJSONTyped;
/**
 * Check if a given object implements the ListIssuanceScenarios500Response interface.
 */
function instanceOfListIssuanceScenarios500Response(value) {
    return true;
}
function ListIssuanceScenarios500ResponseFromJSON(json) {
    return ListIssuanceScenarios500ResponseFromJSONTyped(json, false);
}
function ListIssuanceScenarios500ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'message': json['message'] == null ? undefined : json['message'],
    };
}
function ListIssuanceScenarios500ResponseToJSON(json) {
    return ListIssuanceScenarios500ResponseToJSONTyped(json, false);
}
function ListIssuanceScenarios500ResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'message': value['message'],
    };
}
//# sourceMappingURL=ListIssuanceScenarios500Response.js.map