'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfListIssuanceFlows400Response = instanceOfListIssuanceFlows400Response;
exports.ListIssuanceFlows400ResponseFromJSON = ListIssuanceFlows400ResponseFromJSON;
exports.ListIssuanceFlows400ResponseFromJSONTyped = ListIssuanceFlows400ResponseFromJSONTyped;
exports.ListIssuanceFlows400ResponseToJSON = ListIssuanceFlows400ResponseToJSON;
exports.ListIssuanceFlows400ResponseToJSONTyped = ListIssuanceFlows400ResponseToJSONTyped;
/**
 * Check if a given object implements the ListIssuanceFlows400Response interface.
 */
function instanceOfListIssuanceFlows400Response(value) {
    return true;
}
function ListIssuanceFlows400ResponseFromJSON(json) {
    return ListIssuanceFlows400ResponseFromJSONTyped(json, false);
}
function ListIssuanceFlows400ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'message': json['message'] == null ? undefined : json['message'],
    };
}
function ListIssuanceFlows400ResponseToJSON(json) {
    return ListIssuanceFlows400ResponseToJSONTyped(json, false);
}
function ListIssuanceFlows400ResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'message': value['message'],
    };
}
//# sourceMappingURL=ListIssuanceFlows400Response.js.map