"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfListIssuanceFlows403Response = instanceOfListIssuanceFlows403Response;
exports.ListIssuanceFlows403ResponseFromJSON = ListIssuanceFlows403ResponseFromJSON;
exports.ListIssuanceFlows403ResponseFromJSONTyped = ListIssuanceFlows403ResponseFromJSONTyped;
exports.ListIssuanceFlows403ResponseToJSON = ListIssuanceFlows403ResponseToJSON;
exports.ListIssuanceFlows403ResponseToJSONTyped = ListIssuanceFlows403ResponseToJSONTyped;
/**
 * Check if a given object implements the ListIssuanceFlows403Response interface.
 */
function instanceOfListIssuanceFlows403Response(value) {
    return true;
}
function ListIssuanceFlows403ResponseFromJSON(json) {
    return ListIssuanceFlows403ResponseFromJSONTyped(json, false);
}
function ListIssuanceFlows403ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'message': json['message'] == null ? undefined : json['message'],
    };
}
function ListIssuanceFlows403ResponseToJSON(json) {
    return ListIssuanceFlows403ResponseToJSONTyped(json, false);
}
function ListIssuanceFlows403ResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'message': value['message'],
    };
}
//# sourceMappingURL=ListIssuanceFlows403Response.js.map