/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ListIssuanceScenarios500Response
 */
export interface ListIssuanceScenarios500Response {
    /**
     *
     * @type {string}
     * @memberof ListIssuanceScenarios500Response
     */
    message?: string;
}
/**
 * Check if a given object implements the ListIssuanceScenarios500Response interface.
 */
export declare function instanceOfListIssuanceScenarios500Response(value: object): value is ListIssuanceScenarios500Response;
export declare function ListIssuanceScenarios500ResponseFromJSON(json: any): ListIssuanceScenarios500Response;
export declare function ListIssuanceScenarios500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListIssuanceScenarios500Response;
export declare function ListIssuanceScenarios500ResponseToJSON(json: any): ListIssuanceScenarios500Response;
export declare function ListIssuanceScenarios500ResponseToJSONTyped(value?: ListIssuanceScenarios500Response | null, ignoreDiscriminator?: boolean): any;
//# sourceMappingURL=ListIssuanceScenarios500Response.d.ts.map