/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Overlay Capture Architecture representation of a credential
 * @export
 * @interface OCARepresentation
 */
export interface OCARepresentation {
  /**
   * Unique identifier for the credential representation
   * @type {string}
   * @memberof OCARepresentation
   */
  id: string
  /**
   * Date and time the credential representation was created
   * @type {Date}
   * @memberof OCARepresentation
   */
  createdAt: Date
  /**
   * Date and time the credential representation was last updated
   * @type {Date}
   * @memberof OCARepresentation
   */
  updatedAt: Date
  /**
   * Credential definition identifier in the OCA format
   * @type {string}
   * @memberof OCARepresentation
   */
  credDefId: string
  /**
   * Schema identifier in the OCA format
   * @type {string}
   * @memberof OCARepresentation
   */
  schemaId: string
  /**
   * URL to the OCA bundle for this representation
   * @type {string}
   * @memberof OCARepresentation
   */
  ocaBundleUrl?: string
}
/**
 * Check if a given object implements the OCARepresentation interface.
 */
export declare function instanceOfOCARepresentation(value: object): value is OCARepresentation
export declare function OCARepresentationFromJSON(json: any): OCARepresentation
export declare function OCARepresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): OCARepresentation
export declare function OCARepresentationToJSON(json: any): OCARepresentation
export declare function OCARepresentationToJSONTyped(
  value?: OCARepresentation | null,
  ignoreDiscriminator?: boolean
): any
//# sourceMappingURL=OCARepresentation.d.ts.map
