'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPersonasResponse = instanceOfPersonasResponse;
exports.PersonasResponseFromJSON = PersonasResponseFromJSON;
exports.PersonasResponseFromJSONTyped = PersonasResponseFromJSONTyped;
exports.PersonasResponseToJSON = PersonasResponseToJSON;
exports.PersonasResponseToJSONTyped = PersonasResponseToJSONTyped;
const Persona_1 = require("./Persona");
/**
 * Check if a given object implements the PersonasResponse interface.
 */
function instanceOfPersonasResponse(value) {
    return true;
}
function PersonasResponseFromJSON(json) {
    return PersonasResponseFromJSONTyped(json, false);
}
function PersonasResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'personas': json['personas'] == null ? undefined : (json['personas'].map(Persona_1.PersonaFromJSON)),
    };
}
function PersonasResponseToJSON(json) {
    return PersonasResponseToJSONTyped(json, false);
}
function PersonasResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'personas': value['personas'] == null ? undefined : (value['personas'].map(Persona_1.PersonaToJSON)),
    };
}
//# sourceMappingURL=PersonasResponse.js.map