'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPersonaResponse = instanceOfPersonaResponse;
exports.PersonaResponseFromJSON = PersonaResponseFromJSON;
exports.PersonaResponseFromJSONTyped = PersonaResponseFromJSONTyped;
exports.PersonaResponseToJSON = PersonaResponseToJSON;
exports.PersonaResponseToJSONTyped = PersonaResponseToJSONTyped;
const Persona_1 = require("./Persona");
/**
 * Check if a given object implements the PersonaResponse interface.
 */
function instanceOfPersonaResponse(value) {
    return true;
}
function PersonaResponseFromJSON(json) {
    return PersonaResponseFromJSONTyped(json, false);
}
function PersonaResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'persona': json['persona'] == null ? undefined : (0, Persona_1.PersonaFromJSON)(json['persona']),
    };
}
function PersonaResponseToJSON(json) {
    return PersonaResponseToJSONTyped(json, false);
}
function PersonaResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'persona': (0, Persona_1.PersonaToJSON)(value['persona']),
    };
}
//# sourceMappingURL=PersonaResponse.js.map