/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Persona } from './Persona'

/**
 *
 * @export
 * @interface PersonaResponse
 */
export interface PersonaResponse {
  /**
   *
   * @type {Persona}
   * @memberof PersonaResponse
   */
  persona?: Persona
}
/**
 * Check if a given object implements the PersonaResponse interface.
 */
export declare function instanceOfPersonaResponse(value: object): value is PersonaResponse
export declare function PersonaResponseFromJSON(json: any): PersonaResponse
export declare function PersonaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonaResponse
export declare function PersonaResponseToJSON(json: any): PersonaResponse
export declare function PersonaResponseToJSONTyped(value?: PersonaResponse | null, ignoreDiscriminator?: boolean): any
//# sourceMappingURL=PersonaResponse.d.ts.map
