"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPersonaRequest = instanceOfPersonaRequest;
exports.PersonaRequestFromJSON = PersonaRequestFromJSON;
exports.PersonaRequestFromJSONTyped = PersonaRequestFromJSONTyped;
exports.PersonaRequestToJSON = PersonaRequestToJSON;
exports.PersonaRequestToJSONTyped = PersonaRequestToJSONTyped;
/**
 * Check if a given object implements the PersonaRequest interface.
 */
function instanceOfPersonaRequest(value) {
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('role' in value) || value['role'] === undefined)
        return false;
    return true;
}
function PersonaRequestFromJSON(json) {
    return PersonaRequestFromJSONTyped(json, false);
}
function PersonaRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'],
        'role': json['role'],
        'description': json['description'] == null ? undefined : json['description'],
        'headshotImage': json['headshotImage'] == null ? undefined : json['headshotImage'],
        'bodyImage': json['bodyImage'] == null ? undefined : json['bodyImage'],
        'hidden': json['hidden'] == null ? undefined : json['hidden'],
    };
}
function PersonaRequestToJSON(json) {
    return PersonaRequestToJSONTyped(json, false);
}
function PersonaRequestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'role': value['role'],
        'description': value['description'],
        'headshotImage': value['headshotImage'],
        'bodyImage': value['bodyImage'],
        'hidden': value['hidden'],
    };
}
//# sourceMappingURL=PersonaRequest.js.map