"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPresentationScenariosResponse = instanceOfPresentationScenariosResponse;
exports.PresentationScenariosResponseFromJSON = PresentationScenariosResponseFromJSON;
exports.PresentationScenariosResponseFromJSONTyped = PresentationScenariosResponseFromJSONTyped;
exports.PresentationScenariosResponseToJSON = PresentationScenariosResponseToJSON;
exports.PresentationScenariosResponseToJSONTyped = PresentationScenariosResponseToJSONTyped;
const PresentationScenario_1 = require("./PresentationScenario");
/**
 * Check if a given object implements the PresentationScenariosResponse interface.
 */
function instanceOfPresentationScenariosResponse(value) {
    return true;
}
function PresentationScenariosResponseFromJSON(json) {
    return PresentationScenariosResponseFromJSONTyped(json, false);
}
function PresentationScenariosResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'presentationScenarios': json['presentationScenarios'] == null ? undefined : (json['presentationScenarios'].map(PresentationScenario_1.PresentationScenarioFromJSON)),
    };
}
function PresentationScenariosResponseToJSON(json) {
    return PresentationScenariosResponseToJSONTyped(json, false);
}
function PresentationScenariosResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'presentationScenarios': value['presentationScenarios'] == null ? undefined : (value['presentationScenarios'].map(PresentationScenario_1.PresentationScenarioToJSON)),
    };
}
//# sourceMappingURL=PresentationScenariosResponse.js.map