"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPresentationScenarioResponse = instanceOfPresentationScenarioResponse;
exports.PresentationScenarioResponseFromJSON = PresentationScenarioResponseFromJSON;
exports.PresentationScenarioResponseFromJSONTyped = PresentationScenarioResponseFromJSONTyped;
exports.PresentationScenarioResponseToJSON = PresentationScenarioResponseToJSON;
exports.PresentationScenarioResponseToJSONTyped = PresentationScenarioResponseToJSONTyped;
const PresentationScenario_1 = require("./PresentationScenario");
/**
 * Check if a given object implements the PresentationScenarioResponse interface.
 */
function instanceOfPresentationScenarioResponse(value) {
    return true;
}
function PresentationScenarioResponseFromJSON(json) {
    return PresentationScenarioResponseFromJSONTyped(json, false);
}
function PresentationScenarioResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'presentationScenario': json['presentationScenario'] == null ? undefined : (0, PresentationScenario_1.PresentationScenarioFromJSON)(json['presentationScenario']),
    };
}
function PresentationScenarioResponseToJSON(json) {
    return PresentationScenarioResponseToJSONTyped(json, false);
}
function PresentationScenarioResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'presentationScenario': (0, PresentationScenario_1.PresentationScenarioToJSON)(value['presentationScenario']),
    };
}
//# sourceMappingURL=PresentationScenarioResponse.js.map