'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RelyingPartyType = void 0;
exports.instanceOfRelyingPartyType = instanceOfRelyingPartyType;
exports.RelyingPartyTypeFromJSON = RelyingPartyTypeFromJSON;
exports.RelyingPartyTypeFromJSONTyped = RelyingPartyTypeFromJSONTyped;
exports.RelyingPartyTypeToJSON = RelyingPartyTypeToJSON;
exports.RelyingPartyTypeToJSONTyped = RelyingPartyTypeToJSONTyped;
/**
 * Types of supported relying parties
 * @export
 */
exports.RelyingPartyType = {
    Aries: 'ARIES'
};
function instanceOfRelyingPartyType(value) {
    for (const key in exports.RelyingPartyType) {
        if (Object.prototype.hasOwnProperty.call(exports.RelyingPartyType, key)) {
            if (exports.RelyingPartyType[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function RelyingPartyTypeFromJSON(json) {
    return RelyingPartyTypeFromJSONTyped(json, false);
}
function RelyingPartyTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function RelyingPartyTypeToJSON(value) {
    return value;
}
function RelyingPartyTypeToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
//# sourceMappingURL=RelyingPartyType.js.map