/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Asset } from './Asset'
import type { CredentialDefinition } from './CredentialDefinition'
import type { RelyingPartyType } from './RelyingPartyType'
/**
 *
 * @export
 * @interface RelyingParty
 */
export interface RelyingParty {
  /**
   * Unique identifier for the relying party
   * @type {string}
   * @memberof RelyingParty
   */
  id: string
  /**
   * Name of the relying party
   * @type {string}
   * @memberof RelyingParty
   */
  name: string
  /**
   * Detailed description of the relying party
   * @type {string}
   * @memberof RelyingParty
   */
  description: string
  /**
   *
   * @type {RelyingPartyType}
   * @memberof RelyingParty
   */
  type: RelyingPartyType
  /**
   * Organization the relying party belongs to
   * @type {string}
   * @memberof RelyingParty
   */
  organization?: string
  /**
   * The asset id
   * @type {string}
   * @memberof RelyingParty
   */
  logoId?: string
  /**
   *
   * @type {Asset}
   * @memberof RelyingParty
   */
  logo?: Asset
  /**
   *
   * @type {Array<CredentialDefinition>}
   * @memberof RelyingParty
   */
  credentialDefinitions: Array<CredentialDefinition>
  /**
   * Date and time the relying party was created
   * @type {Date}
   * @memberof RelyingParty
   */
  createdAt: Date
  /**
   * Date and time the relying party was last updated
   * @type {Date}
   * @memberof RelyingParty
   */
  updatedAt: Date
}
/**
 * Check if a given object implements the RelyingParty interface.
 */
export declare function instanceOfRelyingParty(value: object): value is RelyingParty
export declare function RelyingPartyFromJSON(json: any): RelyingParty
export declare function RelyingPartyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelyingParty
export declare function RelyingPartyToJSON(json: any): RelyingParty
export declare function RelyingPartyToJSONTyped(value?: RelyingParty | null, ignoreDiscriminator?: boolean): any
//# sourceMappingURL=RelyingParty.d.ts.map
