"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfRelyingParty = instanceOfRelyingParty;
exports.RelyingPartyFromJSON = RelyingPartyFromJSON;
exports.RelyingPartyFromJSONTyped = RelyingPartyFromJSONTyped;
exports.RelyingPartyToJSON = RelyingPartyToJSON;
exports.RelyingPartyToJSONTyped = RelyingPartyToJSONTyped;
const CredentialDefinition_1 = require("./CredentialDefinition");
const Asset_1 = require("./Asset");
const RelyingPartyType_1 = require("./RelyingPartyType");
/**
 * Check if a given object implements the RelyingParty interface.
 */
function instanceOfRelyingParty(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('description' in value) || value['description'] === undefined)
        return false;
    if (!('type' in value) || value['type'] === undefined)
        return false;
    if (!('credentialDefinitions' in value) || value['credentialDefinitions'] === undefined)
        return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined)
        return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined)
        return false;
    return true;
}
function RelyingPartyFromJSON(json) {
    return RelyingPartyFromJSONTyped(json, false);
}
function RelyingPartyFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'type': (0, RelyingPartyType_1.RelyingPartyTypeFromJSON)(json['type']),
        'organization': json['organization'] == null ? undefined : json['organization'],
        'logoId': json['logoId'] == null ? undefined : json['logoId'],
        'logo': json['logo'] == null ? undefined : (0, Asset_1.AssetFromJSON)(json['logo']),
        'credentialDefinitions': (json['credentialDefinitions'].map(CredentialDefinition_1.CredentialDefinitionFromJSON)),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}
function RelyingPartyToJSON(json) {
    return RelyingPartyToJSONTyped(json, false);
}
function RelyingPartyToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'type': (0, RelyingPartyType_1.RelyingPartyTypeToJSON)(value['type']),
        'organization': value['organization'],
        'logoId': value['logoId'],
        'logo': (0, Asset_1.AssetToJSON)(value['logo']),
        'credentialDefinitions': (value['credentialDefinitions'].map(CredentialDefinition_1.CredentialDefinitionToJSON)),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}
//# sourceMappingURL=RelyingParty.js.map