"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfRelyingPartyResponse = instanceOfRelyingPartyResponse;
exports.RelyingPartyResponseFromJSON = RelyingPartyResponseFromJSON;
exports.RelyingPartyResponseFromJSONTyped = RelyingPartyResponseFromJSONTyped;
exports.RelyingPartyResponseToJSON = RelyingPartyResponseToJSON;
exports.RelyingPartyResponseToJSONTyped = RelyingPartyResponseToJSONTyped;
const RelyingParty_1 = require("./RelyingParty");
/**
 * Check if a given object implements the RelyingPartyResponse interface.
 */
function instanceOfRelyingPartyResponse(value) {
    return true;
}
function RelyingPartyResponseFromJSON(json) {
    return RelyingPartyResponseFromJSONTyped(json, false);
}
function RelyingPartyResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'relyingParty': json['relyingParty'] == null ? undefined : (0, RelyingParty_1.RelyingPartyFromJSON)(json['relyingParty']),
    };
}
function RelyingPartyResponseToJSON(json) {
    return RelyingPartyResponseToJSONTyped(json, false);
}
function RelyingPartyResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'relyingParty': (0, RelyingParty_1.RelyingPartyToJSON)(value['relyingParty']),
    };
}
//# sourceMappingURL=RelyingPartyResponse.js.map