/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { RelyingParty } from './RelyingParty';
/**
 *
 * @export
 * @interface RelyingPartyResponse
 */
export interface RelyingPartyResponse {
    /**
     *
     * @type {RelyingParty}
     * @memberof RelyingPartyResponse
     */
    relyingParty?: RelyingParty;
}
/**
 * Check if a given object implements the RelyingPartyResponse interface.
 */
export declare function instanceOfRelyingPartyResponse(value: object): value is RelyingPartyResponse;
export declare function RelyingPartyResponseFromJSON(json: any): RelyingPartyResponse;
export declare function RelyingPartyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelyingPartyResponse;
export declare function RelyingPartyResponseToJSON(json: any): RelyingPartyResponse;
export declare function RelyingPartyResponseToJSONTyped(value?: RelyingPartyResponse | null, ignoreDiscriminator?: boolean): any;
//# sourceMappingURL=RelyingPartyResponse.d.ts.map