"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfRevocationInfo = instanceOfRevocationInfo;
exports.RevocationInfoFromJSON = RevocationInfoFromJSON;
exports.RevocationInfoFromJSONTyped = RevocationInfoFromJSONTyped;
exports.RevocationInfoToJSON = RevocationInfoToJSON;
exports.RevocationInfoToJSONTyped = RevocationInfoToJSONTyped;
/**
 * Check if a given object implements the RevocationInfo interface.
 */
function instanceOfRevocationInfo(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('title' in value) || value['title'] === undefined)
        return false;
    if (!('description' in value) || value['description'] === undefined)
        return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined)
        return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined)
        return false;
    return true;
}
function RevocationInfoFromJSON(json) {
    return RevocationInfoFromJSONTyped(json, false);
}
function RevocationInfoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}
function RevocationInfoToJSON(json) {
    return RevocationInfoToJSONTyped(json, false);
}
function RevocationInfoToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}
//# sourceMappingURL=RevocationInfo.js.map