"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ScenarioType = void 0;
exports.instanceOfScenarioType = instanceOfScenarioType;
exports.ScenarioTypeFromJSON = ScenarioTypeFromJSON;
exports.ScenarioTypeFromJSONTyped = ScenarioTypeFromJSONTyped;
exports.ScenarioTypeToJSON = ScenarioTypeToJSON;
exports.ScenarioTypeToJSONTyped = ScenarioTypeToJSONTyped;
/**
 * Types of supported scenarios
 * @export
 */
exports.ScenarioType = {
    Issuance: 'ISSUANCE',
    Presentation: 'PRESENTATION'
};
function instanceOfScenarioType(value) {
    for (const key in exports.ScenarioType) {
        if (Object.prototype.hasOwnProperty.call(exports.ScenarioType, key)) {
            if (exports.ScenarioType[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function ScenarioTypeFromJSON(json) {
    return ScenarioTypeFromJSONTyped(json, false);
}
function ScenarioTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function ScenarioTypeToJSON(value) {
    return value;
}
function ScenarioTypeToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
//# sourceMappingURL=ScenarioType.js.map