'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShowcasePersonasInnerFromJSON = ShowcasePersonasInnerFromJSON;
exports.ShowcasePersonasInnerFromJSONTyped = ShowcasePersonasInnerFromJSONTyped;
exports.ShowcasePersonasInnerToJSON = ShowcasePersonasInnerToJSON;
exports.ShowcasePersonasInnerToJSONTyped = ShowcasePersonasInnerToJSONTyped;
const Id_1 = require("./Id");
const Persona_1 = require("./Persona");
function ShowcasePersonasInnerFromJSON(json) {
    return ShowcasePersonasInnerFromJSONTyped(json, false);
}
function ShowcasePersonasInnerFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    if ((0, Id_1.instanceOfId)(json)) {
        return (0, Id_1.IdFromJSONTyped)(json, true);
    }
    if ((0, Persona_1.instanceOfPersona)(json)) {
        return (0, Persona_1.PersonaFromJSONTyped)(json, true);
    }
    return {};
}
function ShowcasePersonasInnerToJSON(json) {
    return ShowcasePersonasInnerToJSONTyped(json, false);
}
function ShowcasePersonasInnerToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    if ((0, Id_1.instanceOfId)(value)) {
        return (0, Id_1.IdToJSON)(value);
    }
    if ((0, Persona_1.instanceOfPersona)(value)) {
        return (0, Persona_1.PersonaToJSON)(value);
    }
    return {};
}
//# sourceMappingURL=ShowcasePersonasInner.js.map