'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfShowcaseResponse = instanceOfShowcaseResponse;
exports.ShowcaseResponseFromJSON = ShowcaseResponseFromJSON;
exports.ShowcaseResponseFromJSONTyped = ShowcaseResponseFromJSONTyped;
exports.ShowcaseResponseToJSON = ShowcaseResponseToJSON;
exports.ShowcaseResponseToJSONTyped = ShowcaseResponseToJSONTyped;
const Showcase_1 = require("./Showcase");
/**
 * Check if a given object implements the ShowcaseResponse interface.
 */
function instanceOfShowcaseResponse(value) {
    return true;
}
function ShowcaseResponseFromJSON(json) {
    return ShowcaseResponseFromJSONTyped(json, false);
}
function ShowcaseResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'showcase': json['showcase'] == null ? undefined : (0, Showcase_1.ShowcaseFromJSON)(json['showcase']),
    };
}
function ShowcaseResponseToJSON(json) {
    return ShowcaseResponseToJSONTyped(json, false);
}
function ShowcaseResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'showcase': (0, Showcase_1.ShowcaseToJSON)(value['showcase']),
    };
}
//# sourceMappingURL=ShowcaseResponse.js.map