/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Id } from './Id';
import type { Scenario } from './Scenario';
/**
 * @type ShowcaseScenariosInner
 *
 * @export
 */
export type ShowcaseScenariosInner = Id | Scenario;
export declare function ShowcaseScenariosInnerFromJSON(json: any): ShowcaseScenariosInner;
export declare function ShowcaseScenariosInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowcaseScenariosInner;
export declare function ShowcaseScenariosInnerToJSON(json: any): any;
export declare function ShowcaseScenariosInnerToJSONTyped(value?: ShowcaseScenariosInner | null, ignoreDiscriminator?: boolean): any;
//# sourceMappingURL=ShowcaseScenariosInner.d.ts.map