"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfShowcasesResponse = instanceOfShowcasesResponse;
exports.ShowcasesResponseFromJSON = ShowcasesResponseFromJSON;
exports.ShowcasesResponseFromJSONTyped = ShowcasesResponseFromJSONTyped;
exports.ShowcasesResponseToJSON = ShowcasesResponseToJSON;
exports.ShowcasesResponseToJSONTyped = ShowcasesResponseToJSONTyped;
const Showcase_1 = require("./Showcase");
/**
 * Check if a given object implements the ShowcasesResponse interface.
 */
function instanceOfShowcasesResponse(value) {
    return true;
}
function ShowcasesResponseFromJSON(json) {
    return ShowcasesResponseFromJSONTyped(json, false);
}
function ShowcasesResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'showcases': json['showcases'] == null ? undefined : (json['showcases'].map(Showcase_1.ShowcaseFromJSON)),
    };
}
function ShowcasesResponseToJSON(json) {
    return ShowcasesResponseToJSONTyped(json, false);
}
function ShowcasesResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'showcases': value['showcases'] == null ? undefined : (value['showcases'].map(Showcase_1.ShowcaseToJSON)),
    };
}
//# sourceMappingURL=ShowcasesResponse.js.map