/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Showcase } from './Showcase'

/**
 *
 * @export
 * @interface ShowcasesResponse
 */
export interface ShowcasesResponse {
  /**
   * List of showcases
   * @type {Array<Showcase>}
   * @memberof ShowcasesResponse
   */
  showcases?: Array<Showcase>
}
/**
 * Check if a given object implements the ShowcasesResponse interface.
 */
export declare function instanceOfShowcasesResponse(value: object): value is ShowcasesResponse
export declare function ShowcasesResponseFromJSON(json: any): ShowcasesResponse
export declare function ShowcasesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowcasesResponse
export declare function ShowcasesResponseToJSON(json: any): ShowcasesResponse
export declare function ShowcasesResponseToJSONTyped(
  value?: ShowcasesResponse | null,
  ignoreDiscriminator?: boolean
): any
//# sourceMappingURL=ShowcasesResponse.d.ts.map
