'use strict'
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShowcaseCredentialDefinitionsInnerFromJSON = ShowcaseCredentialDefinitionsInnerFromJSON;
exports.ShowcaseCredentialDefinitionsInnerFromJSONTyped = ShowcaseCredentialDefinitionsInnerFromJSONTyped;
exports.ShowcaseCredentialDefinitionsInnerToJSON = ShowcaseCredentialDefinitionsInnerToJSON;
exports.ShowcaseCredentialDefinitionsInnerToJSONTyped = ShowcaseCredentialDefinitionsInnerToJSONTyped;
const CredentialDefinition_1 = require("./CredentialDefinition");
const Id_1 = require("./Id");
function ShowcaseCredentialDefinitionsInnerFromJSON(json) {
    return ShowcaseCredentialDefinitionsInnerFromJSONTyped(json, false);
}
function ShowcaseCredentialDefinitionsInnerFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    if ((0, CredentialDefinition_1.instanceOfCredentialDefinition)(json)) {
        return (0, CredentialDefinition_1.CredentialDefinitionFromJSONTyped)(json, true);
    }
    if ((0, Id_1.instanceOfId)(json)) {
        return (0, Id_1.IdFromJSONTyped)(json, true);
    }
    return {};
}
function ShowcaseCredentialDefinitionsInnerToJSON(json) {
    return ShowcaseCredentialDefinitionsInnerToJSONTyped(json, false);
}
function ShowcaseCredentialDefinitionsInnerToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    if ((0, CredentialDefinition_1.instanceOfCredentialDefinition)(value)) {
        return (0, CredentialDefinition_1.CredentialDefinitionToJSON)(value);
    }
    if ((0, Id_1.instanceOfId)(value)) {
        return (0, Id_1.IdToJSON)(value);
    }
    return {};
}
//# sourceMappingURL=ShowcaseCredentialDefinitionsInner.js.map