/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Types of supported origins
 * @export
 */
export declare const Source: {
    readonly Imported: "IMPORTED";
    readonly Created: "CREATED";
};
export type Source = typeof Source[keyof typeof Source];
export declare function instanceOfSource(value: any): boolean;
export declare function SourceFromJSON(json: any): Source;
export declare function SourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Source;
export declare function SourceToJSON(value?: Source | null): any;
export declare function SourceToJSONTyped(value: any, ignoreDiscriminator: boolean): Source;
//# sourceMappingURL=Source.d.ts.map