"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Source = void 0;
exports.instanceOfSource = instanceOfSource;
exports.SourceFromJSON = SourceFromJSON;
exports.SourceFromJSONTyped = SourceFromJSONTyped;
exports.SourceToJSON = SourceToJSON;
exports.SourceToJSONTyped = SourceToJSONTyped;
/**
 * Types of supported origins
 * @export
 */
exports.Source = {
    Imported: 'IMPORTED',
    Created: 'CREATED'
};
function instanceOfSource(value) {
    for (const key in exports.Source) {
        if (Object.prototype.hasOwnProperty.call(exports.Source, key)) {
            if (exports.Source[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function SourceFromJSON(json) {
    return SourceFromJSONTyped(json, false);
}
function SourceFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function SourceToJSON(value) {
    return value;
}
function SourceToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
//# sourceMappingURL=Source.js.map