"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.StepType = void 0;
exports.instanceOfStepType = instanceOfStepType;
exports.StepTypeFromJSON = StepTypeFromJSON;
exports.StepTypeFromJSONTyped = StepTypeFromJSONTyped;
exports.StepTypeToJSON = StepTypeToJSON;
exports.StepTypeToJSONTyped = StepTypeToJSONTyped;
/**
 * Type of step in the scenario
 * @export
 */
exports.StepType = {
    HumanTask: 'HUMAN_TASK',
    Service: 'SERVICE',
    Scenario: 'SCENARIO'
};
function instanceOfStepType(value) {
    for (const key in exports.StepType) {
        if (Object.prototype.hasOwnProperty.call(exports.StepType, key)) {
            if (exports.StepType[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function StepTypeFromJSON(json) {
    return StepTypeFromJSONTyped(json, false);
}
function StepTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function StepTypeToJSON(value) {
    return value;
}
function StepTypeToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
//# sourceMappingURL=StepType.js.map