/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { StepAction } from './StepAction'
/**
 *
 * @export
 * @interface StepActionsResponse
 */
export interface StepActionsResponse {
  /**
   *
   * @type {Array<StepAction>}
   * @memberof StepActionsResponse
   */
  actions?: Array<StepAction>
}
/**
 * Check if a given object implements the StepActionsResponse interface.
 */
export declare function instanceOfStepActionsResponse(value: object): value is StepActionsResponse
export declare function StepActionsResponseFromJSON(json: any): StepActionsResponse
export declare function StepActionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepActionsResponse
export declare function StepActionsResponseToJSON(json: any): StepActionsResponse
export declare function StepActionsResponseToJSONTyped(
  value?: StepActionsResponse | null,
  ignoreDiscriminator?: boolean
): any
//# sourceMappingURL=StepActionsResponse.d.ts.map
