"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.StepRequestActionsInnerFromJSON = StepRequestActionsInnerFromJSON;
exports.StepRequestActionsInnerFromJSONTyped = StepRequestActionsInnerFromJSONTyped;
exports.StepRequestActionsInnerToJSON = StepRequestActionsInnerToJSON;
exports.StepRequestActionsInnerToJSONTyped = StepRequestActionsInnerToJSONTyped;
const AriesOOBActionRequest_1 = require("./AriesOOBActionRequest");
function StepRequestActionsInnerFromJSON(json) {
    return StepRequestActionsInnerFromJSONTyped(json, false);
}
function StepRequestActionsInnerFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    if ((0, AriesOOBActionRequest_1.instanceOfAriesOOBActionRequest)(json)) {
        return (0, AriesOOBActionRequest_1.AriesOOBActionRequestFromJSONTyped)(json, true);
    }
    return {};
}
function StepRequestActionsInnerToJSON(json) {
    return StepRequestActionsInnerToJSONTyped(json, false);
}
function StepRequestActionsInnerToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    if ((0, AriesOOBActionRequest_1.instanceOfAriesOOBActionRequest)(value)) {
        return (0, AriesOOBActionRequest_1.AriesOOBActionRequestToJSON)(value);
    }
    return {};
}
//# sourceMappingURL=StepRequestActionsInner.js.map