"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfStepsResponse = instanceOfStepsResponse;
exports.StepsResponseFromJSON = StepsResponseFromJSON;
exports.StepsResponseFromJSONTyped = StepsResponseFromJSONTyped;
exports.StepsResponseToJSON = StepsResponseToJSON;
exports.StepsResponseToJSONTyped = StepsResponseToJSONTyped;
const Step_1 = require("./Step");
/**
 * Check if a given object implements the StepsResponse interface.
 */
function instanceOfStepsResponse(value) {
    return true;
}
function StepsResponseFromJSON(json) {
    return StepsResponseFromJSONTyped(json, false);
}
function StepsResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'steps': json['steps'] == null ? undefined : (json['steps'].map(Step_1.StepFromJSON)),
    };
}
function StepsResponseToJSON(json) {
    return StepsResponseToJSONTyped(json, false);
}
function StepsResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'steps': value['steps'] == null ? undefined : (value['steps'].map(Step_1.StepToJSON)),
    };
}
//# sourceMappingURL=StepsResponse.js.map