"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfStep = instanceOfStep;
exports.StepFromJSON = StepFromJSON;
exports.StepFromJSONTyped = StepFromJSONTyped;
exports.StepToJSON = StepToJSON;
exports.StepToJSONTyped = StepToJSONTyped;
const StepAction_1 = require("./StepAction");
const StepType_1 = require("./StepType");
const Asset_1 = require("./Asset");
/**
 * Check if a given object implements the Step interface.
 */
function instanceOfStep(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('title' in value) || value['title'] === undefined)
        return false;
    if (!('description' in value) || value['description'] === undefined)
        return false;
    if (!('order' in value) || value['order'] === undefined)
        return false;
    if (!('type' in value) || value['type'] === undefined)
        return false;
    if (!('actions' in value) || value['actions'] === undefined)
        return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined)
        return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined)
        return false;
    return true;
}
function StepFromJSON(json) {
    return StepFromJSONTyped(json, false);
}
function StepFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'order': json['order'],
        'type': (0, StepType_1.StepTypeFromJSON)(json['type']),
        'subScenario': json['subScenario'] == null ? undefined : json['subScenario'],
        'actions': (json['actions'].map(StepAction_1.StepActionFromJSON)),
        'assetId': json['assetId'] == null ? undefined : json['assetId'],
        'asset': json['asset'] == null ? undefined : (0, Asset_1.AssetFromJSON)(json['asset']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}
function StepToJSON(json) {
    return StepToJSONTyped(json, false);
}
function StepToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'order': value['order'],
        'type': (0, StepType_1.StepTypeToJSON)(value['type']),
        'subScenario': value['subScenario'],
        'actions': (value['actions'].map(StepAction_1.StepActionToJSON)),
        'assetId': value['assetId'],
        'asset': (0, Asset_1.AssetToJSON)(value['asset']),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}
//# sourceMappingURL=Step.js.map